-- =============================================================================
-- Purchasing-RR (module PO) — 300: core objects
--   Sequence, setup tables, requisitions, purchase orders, change orders,
--   receiving, accruals, action history, write-gateway registry and log.
--   Design: docs/design/PO_Module_Requirements_Design.md (v1.1)
--
-- Safe to re-run: existing objects are left as they are (ORA-00955 etc. ignored).
-- Run in bcldifc (SQL Developer, F5). Then 301, 302, 303, 304 in order.
-- Suppliers come from the existing RR_SUPPLIER_* tables; nothing is copied.
-- =============================================================================
SET SERVEROUTPUT ON

-- DDL runs in anonymous blocks (not a helper procedure): privileges granted through
-- a role (CREATE TABLE / CREATE SEQUENCE) are not visible inside stored procedures.
-- Already-existing objects are skipped (ORA-00955 / 01430 / 02260 / 02261 / 02275 / 01408).
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE RR_PO_DDL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE RR_PO_SEQ START WITH 6000000001 INCREMENT BY 1 CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

-- Standard WHO columns appended to every table
-- CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN

-- ── SETUP ────────────────────────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_BU_OPTIONS (
    BU_OPTION_ID                NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    BUSINESS_UNIT_ID            NUMBER        NOT NULL,
    FUNCTIONAL_CURRENCY         VARCHAR2(15)  DEFAULT 'AED' NOT NULL,
    DEFAULT_RATE_TYPE           VARCHAR2(30)  DEFAULT 'Corporate' NOT NULL,
    DEFAULT_SHIP_TO_LOCATION_ID NUMBER,
    DEFAULT_BILL_TO_LOCATION_ID NUMBER,
    MATCH_LEVEL_QUANTITY        VARCHAR2(10)  DEFAULT 'THREE_WAY' NOT NULL,
    MATCH_LEVEL_AMOUNT          VARCHAR2(10)  DEFAULT 'TWO_WAY' NOT NULL,
    ACCRUE_AT_RECEIPT_FLAG      VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    RECEIPT_ACCRUAL_ACCOUNT     VARCHAR2(200),
    PRICE_VARIANCE_ACCOUNT      VARCHAR2(200),
    EXCHANGE_GAIN_ACCOUNT       VARCHAR2(200),
    EXCHANGE_LOSS_ACCOUNT       VARCHAR2(200),
    ACCRUAL_WRITE_OFF_ACCOUNT   VARCHAR2(200),
    ACCRUAL_WRITE_OFF_AGE_DAYS  NUMBER,
    OVER_RECEIPT_TOLERANCE_PCT  NUMBER(5,2)   DEFAULT 0 NOT NULL,
    OVER_RECEIPT_ACTION         VARCHAR2(10)  DEFAULT 'REJECT' NOT NULL,
    EARLY_RECEIPT_DAYS          NUMBER,
    INVOICE_QTY_TOLERANCE_PCT   NUMBER(5,2)   DEFAULT 0 NOT NULL,
    INVOICE_PRICE_TOLERANCE_PCT NUMBER(5,2)   DEFAULT 5 NOT NULL,
    INVOICE_AMOUNT_TOLERANCE    NUMBER,
    RECEIPT_CLOSE_TOLERANCE_PCT NUMBER(5,2)   DEFAULT 0 NOT NULL,
    INVOICE_CLOSE_TOLERANCE_PCT NUMBER(5,2)   DEFAULT 0 NOT NULL,
    REQ_APPROVAL_REQUIRED       VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    PO_APPROVAL_REQUIRED        VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CO_REAPPROVAL_THRESHOLD_PCT NUMBER(5,2)   DEFAULT 0 NOT NULL,
    AUTOCREATE_MODE             VARCHAR2(10)  DEFAULT 'MANUAL' NOT NULL,
    REQUIRE_REQUISITION         VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    ALLOW_AFTER_FACT_PO         VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    SOD_BUYER_RECEIVE           VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    BUDGET_CONTROL_LEVEL        VARCHAR2(10)  DEFAULT 'NONE' NOT NULL,
    PO_TERMS_TEXT               CLOB,
    PO_EMAIL_SUBJECT            VARCHAR2(400),
    PO_EMAIL_BODY               CLOB,
    STATUS                      VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_BU_OPTIONS_UK UNIQUE (BUSINESS_UNIT_ID),
    CONSTRAINT RR_PO_BU_OPT_ML_CK  CHECK (MATCH_LEVEL_QUANTITY IN ('TWO_WAY','THREE_WAY') AND MATCH_LEVEL_AMOUNT IN ('TWO_WAY','THREE_WAY')),
    CONSTRAINT RR_PO_BU_OPT_ORA_CK CHECK (OVER_RECEIPT_ACTION IN ('REJECT','WARNING'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_LOCATIONS (
    LOCATION_ID       NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    LOCATION_CODE     VARCHAR2(30)  NOT NULL,
    LOCATION_NAME     VARCHAR2(240) NOT NULL,
    BUSINESS_UNIT_ID  NUMBER,
    ADDRESS_LINE1     VARCHAR2(240), ADDRESS_LINE2 VARCHAR2(240), ADDRESS_LINE3 VARCHAR2(240),
    CITY              VARCHAR2(120), REGION VARCHAR2(120), COUNTRY VARCHAR2(80), PO_BOX VARCHAR2(30),
    CONTACT_NAME      VARCHAR2(240), PHONE VARCHAR2(60), EMAIL VARCHAR2(300),
    SHIP_TO_FLAG      VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    BILL_TO_FLAG      VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DELIVER_TO_FLAG   VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    STATUS            VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_LOCATIONS_UK UNIQUE (LOCATION_CODE)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_CATEGORIES (
    CATEGORY_ID             NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    CATEGORY_CODE           VARCHAR2(40)  NOT NULL,
    CATEGORY_NAME           VARCHAR2(240) NOT NULL,
    PARENT_CATEGORY_ID      NUMBER,
    DEFAULT_NATURAL_ACCOUNT VARCHAR2(30),
    DEFAULT_LINE_TYPE       VARCHAR2(10) DEFAULT 'QUANTITY' NOT NULL,
    DEFAULT_UOM             VARCHAR2(10),
    DEFAULT_TAX_CODE        VARCHAR2(50),
    RECEIPT_REQUIRED_FLAG   VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CAPEX_FLAG              VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REQUESTABLE_FLAG        VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    STATUS                  VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_CATEGORIES_UK UNIQUE (CATEGORY_CODE),
    CONSTRAINT RR_PO_CAT_LT_CK CHECK (DEFAULT_LINE_TYPE IN ('QUANTITY','AMOUNT'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_UOMS (
    UOM_CODE           VARCHAR2(10)  PRIMARY KEY,
    UOM_NAME           VARCHAR2(80)  NOT NULL,
    UOM_CLASS          VARCHAR2(30),
    STATUS             VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_EXPENSE_ITEMS (
    EXPENSE_ITEM_ID            NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    ITEM_CODE                  VARCHAR2(40)  NOT NULL,
    DESCRIPTION                VARCHAR2(240) NOT NULL,
    LONG_DESCRIPTION           VARCHAR2(4000),
    CATEGORY_ID                NUMBER        NOT NULL,
    LINE_TYPE                  VARCHAR2(10)  DEFAULT 'QUANTITY' NOT NULL,
    UOM_CODE                   VARCHAR2(10),
    LIST_PRICE                 NUMBER,
    CURRENCY_CODE              VARCHAR2(15),
    PREFERRED_SUPPLIER_ID      NUMBER,
    PREFERRED_SUPPLIER_SITE_ID NUMBER,
    SUPPLIER_ITEM_NUM          VARCHAR2(60),
    LEAD_TIME_DAYS             NUMBER,
    NATURAL_ACCOUNT_OVERRIDE   VARCHAR2(30),
    TAX_CODE                   VARCHAR2(50),
    INV_ITEM_ID                NUMBER,
    STATUS                     VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_EXP_ITEMS_UK UNIQUE (ITEM_CODE),
    CONSTRAINT RR_PO_EXP_ITEMS_LT_CK CHECK (LINE_TYPE IN ('QUANTITY','AMOUNT'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_BUYERS (
    BUYER_ID          NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    USER_NAME         VARCHAR2(150) NOT NULL,
    BUSINESS_UNIT_ID  NUMBER,
    CATEGORY_ID       NUMBER,
    DIRECT_PO_ALLOWED VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    EMAIL             VARCHAR2(300),
    PHONE             VARCHAR2(60),
    DEFAULT_FLAG      VARCHAR2(1) DEFAULT 'N' NOT NULL,
    STATUS            VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_REQUESTER_DEFAULTS (
    DEFAULT_ID              NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    USER_NAME               VARCHAR2(150) NOT NULL,
    BUSINESS_UNIT_ID        NUMBER        NOT NULL,
    DELIVER_TO_LOCATION_ID  NUMBER,
    CHARGE_ACCOUNT_TEMPLATE VARCHAR2(200) NOT NULL,
    MANAGER_USER_NAME       VARCHAR2(150),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_REQ_DEF_UK UNIQUE (USER_NAME, BUSINESS_UNIT_ID)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_ACCOUNT_RULES (
    RULE_ID          NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    BUSINESS_UNIT_ID NUMBER,
    CATEGORY_ID      NUMBER,
    EXPENSE_ITEM_ID  NUMBER,
    SEGMENT_NUM      NUMBER(2)    NOT NULL,
    SEGMENT_VALUE    VARCHAR2(30) NOT NULL,
    PRIORITY         NUMBER DEFAULT 10 NOT NULL,
    STATUS           VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_ACC_RULES_SEG_CK CHECK (SEGMENT_NUM BETWEEN 1 AND 10)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_DOC_SEQUENCES (
    DOC_SEQ_ID       NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    BUSINESS_UNIT_ID NUMBER       NOT NULL,
    DOC_TYPE         VARCHAR2(10) NOT NULL,
    PREFIX           VARCHAR2(20),
    YEAR_IN_NUMBER   VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    NEXT_NUMBER      NUMBER DEFAULT 1 NOT NULL,
    PAD_LENGTH       NUMBER DEFAULT 5 NOT NULL,
    RESET_YEARLY     VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CURRENT_YEAR     NUMBER(4),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_DOC_SEQ_UK UNIQUE (BUSINESS_UNIT_ID, DOC_TYPE),
    CONSTRAINT RR_PO_DOC_SEQ_TYPE_CK CHECK (DOC_TYPE IN ('REQ','PO','RCV','CO','AGR'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_SUPPLIER_SITE_OPTIONS (
    SITE_OPTION_ID              NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    SUPPLIER_SITE_ID            NUMBER NOT NULL,
    PO_COMMUNICATION            VARCHAR2(10) DEFAULT 'PRINT' NOT NULL,
    PO_EMAIL                    VARCHAR2(300),
    DEFAULT_CURRENCY            VARCHAR2(15),
    MATCH_LEVEL                 VARCHAR2(10),
    INVOICE_QTY_TOLERANCE_PCT   NUMBER(5,2),
    INVOICE_PRICE_TOLERANCE_PCT NUMBER(5,2),
    PURCHASING_HOLD_FLAG        VARCHAR2(1) DEFAULT 'N' NOT NULL,
    HOLD_REASON                 VARCHAR2(400),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_SITE_OPT_UK UNIQUE (SUPPLIER_SITE_ID)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

-- ── REQUISITIONS ─────────────────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_REQ_HEADERS (
    REQ_HEADER_ID       NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    REQ_NUMBER          VARCHAR2(40),
    BUSINESS_UNIT_ID    NUMBER        NOT NULL,
    DESCRIPTION         VARCHAR2(240) NOT NULL,
    JUSTIFICATION       VARCHAR2(2000),
    PREPARER_USER       VARCHAR2(150) NOT NULL,
    URGENT_FLAG         VARCHAR2(1) DEFAULT 'N' NOT NULL,
    STATUS              VARCHAR2(20) DEFAULT 'INCOMPLETE' NOT NULL,
    FUNCTIONAL_CURRENCY VARCHAR2(15) NOT NULL,
    TOTAL_AMOUNT_FUNC   NUMBER DEFAULT 0 NOT NULL,
    APPROVAL_REQUEST_ID NUMBER,
    SUBMITTED_DATE      DATE,
    APPROVED_DATE       DATE,
    FUNDS_STATUS        VARCHAR2(10),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_REQ_H_ST_CK CHECK (STATUS IN ('INCOMPLETE','PENDING_APPROVAL','APPROVED','REJECTED','CANCELLED'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_REQ_LINES (
    REQ_LINE_ID                NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    REQ_HEADER_ID              NUMBER       NOT NULL REFERENCES RR_PO_REQ_HEADERS(REQ_HEADER_ID),
    LINE_NUM                   NUMBER       NOT NULL,
    LINE_TYPE                  VARCHAR2(10) NOT NULL,
    EXPENSE_ITEM_ID            NUMBER,
    CATEGORY_ID                NUMBER       NOT NULL,
    ITEM_DESCRIPTION           VARCHAR2(240) NOT NULL,
    UOM_CODE                   VARCHAR2(10),
    QUANTITY                   NUMBER,
    UNIT_PRICE                 NUMBER,
    AMOUNT                     NUMBER       NOT NULL,
    CURRENCY_CODE              VARCHAR2(15) NOT NULL,
    RATE_TYPE                  VARCHAR2(30),
    RATE_DATE                  DATE,
    RATE                       NUMBER DEFAULT 1 NOT NULL,
    AMOUNT_FUNC                NUMBER       NOT NULL,
    TAX_CODE                   VARCHAR2(50),
    NEED_BY_DATE               DATE         NOT NULL,
    DELIVER_TO_LOCATION_ID     NUMBER,
    REQUESTER_USER             VARCHAR2(150) NOT NULL,
    SUGGESTED_SUPPLIER_ID      NUMBER,
    SUGGESTED_SUPPLIER_SITE_ID NUMBER,
    SUGGESTED_SUPPLIER_NAME    VARCHAR2(360),
    SUPPLIER_ITEM_NUM          VARCHAR2(60),
    NOTE_TO_BUYER              VARCHAR2(1000),
    BUYER_ID                   NUMBER,
    LINE_STATUS                VARCHAR2(15) DEFAULT 'OPEN' NOT NULL,
    PO_LINE_ID                 NUMBER,
    AGREEMENT_LINE_ID          NUMBER,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_REQ_L_UK UNIQUE (REQ_HEADER_ID, LINE_NUM),
    CONSTRAINT RR_PO_REQ_L_LT_CK CHECK (LINE_TYPE IN ('QUANTITY','AMOUNT')),
    CONSTRAINT RR_PO_REQ_L_ST_CK CHECK (LINE_STATUS IN ('OPEN','ON_PO','RETURNED','CANCELLED'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_REQ_DISTRIBUTIONS (
    REQ_DISTRIBUTION_ID   NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    REQ_LINE_ID           NUMBER NOT NULL REFERENCES RR_PO_REQ_LINES(REQ_LINE_ID),
    DIST_NUM              NUMBER NOT NULL,
    PERCENT               NUMBER(7,4) NOT NULL,
    QUANTITY              NUMBER,
    AMOUNT                NUMBER NOT NULL,
    CHARGE_ACCOUNT        VARCHAR2(200) NOT NULL,
    BUDGET_DATE           DATE,
    FUNDS_RESERVED_AMOUNT NUMBER,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

-- ── PURCHASE ORDERS ──────────────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_HEADERS (
    PO_HEADER_ID        NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    PO_NUMBER           VARCHAR2(40)  NOT NULL,
    REVISION_NUM        NUMBER DEFAULT 0 NOT NULL,
    BUSINESS_UNIT_ID    NUMBER        NOT NULL,
    PO_TYPE             VARCHAR2(15) DEFAULT 'STANDARD' NOT NULL,
    ORIGIN              VARCHAR2(15) DEFAULT 'MANUAL' NOT NULL,
    SUPPLIER_ID         NUMBER        NOT NULL,
    SUPPLIER_SITE_ID    NUMBER        NOT NULL,
    SUPPLIER_CONTACT    VARCHAR2(240),
    BUYER_ID            NUMBER,
    BUYER_USER          VARCHAR2(150),
    CURRENCY_CODE       VARCHAR2(15)  NOT NULL,
    RATE_TYPE           VARCHAR2(30),
    RATE_DATE           DATE,
    RATE                NUMBER DEFAULT 1 NOT NULL,
    PAYMENT_TERMS       VARCHAR2(240),
    PAYMENT_TERMS_ID    NUMBER,
    SHIP_TO_LOCATION_ID NUMBER,
    BILL_TO_LOCATION_ID NUMBER,
    DESCRIPTION         VARCHAR2(240),
    NOTE_TO_SUPPLIER    VARCHAR2(2000),
    DOCUMENT_STATUS     VARCHAR2(20) DEFAULT 'INCOMPLETE' NOT NULL,
    CLOSURE_STATUS      VARCHAR2(25) DEFAULT 'OPEN' NOT NULL,
    HOLD_FLAG           VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    HOLD_REASON         VARCHAR2(400),
    TOTAL_AMOUNT        NUMBER DEFAULT 0 NOT NULL,
    TOTAL_AMOUNT_FUNC   NUMBER DEFAULT 0 NOT NULL,
    TOTAL_TAX_ESTIMATE  NUMBER,
    APPROVAL_REQUEST_ID NUMBER,
    SUBMITTED_DATE      DATE,
    APPROVED_DATE       DATE,
    COMMUNICATED_DATE   DATE,
    ACCEPTANCE_REQUIRED VARCHAR2(1) DEFAULT 'N' NOT NULL,
    ACCEPTED_DATE       DATE,
    AGREEMENT_ID        NUMBER,
    AFTER_FACT_FLAG     VARCHAR2(1) DEFAULT 'N' NOT NULL,
    LEGACY_PO_NUMBER    VARCHAR2(60),
    CANCEL_REASON       VARCHAR2(400),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_HEADERS_UK UNIQUE (BUSINESS_UNIT_ID, PO_NUMBER),
    CONSTRAINT RR_PO_H_DS_CK CHECK (DOCUMENT_STATUS IN ('INCOMPLETE','PENDING_APPROVAL','APPROVED','REJECTED','CANCELLED')),
    CONSTRAINT RR_PO_H_CS_CK CHECK (CLOSURE_STATUS IN ('OPEN','CLOSED_FOR_RECEIVING','CLOSED_FOR_INVOICING','CLOSED','FINALLY_CLOSED'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_LINES (
    PO_LINE_ID        NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    PO_HEADER_ID      NUMBER        NOT NULL REFERENCES RR_PO_HEADERS(PO_HEADER_ID),
    LINE_NUM          NUMBER        NOT NULL,
    LINE_TYPE         VARCHAR2(10)  NOT NULL,
    EXPENSE_ITEM_ID   NUMBER,
    CATEGORY_ID       NUMBER        NOT NULL,
    ITEM_DESCRIPTION  VARCHAR2(240) NOT NULL,
    SUPPLIER_ITEM_NUM VARCHAR2(60),
    UOM_CODE          VARCHAR2(10),
    QUANTITY          NUMBER,
    UNIT_PRICE        NUMBER,
    AMOUNT            NUMBER        NOT NULL,
    TAX_CODE          VARCHAR2(50),
    LINE_STATUS       VARCHAR2(15) DEFAULT 'OPEN' NOT NULL,
    CANCEL_REASON     VARCHAR2(400),
    CAPEX_FLAG        VARCHAR2(1) DEFAULT 'N' NOT NULL,
    AGREEMENT_LINE_ID NUMBER,
    NOTE_TO_SUPPLIER  VARCHAR2(1000),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_LINES_UK UNIQUE (PO_HEADER_ID, LINE_NUM),
    CONSTRAINT RR_PO_L_LT_CK CHECK (LINE_TYPE IN ('QUANTITY','AMOUNT')),
    CONSTRAINT RR_PO_L_ST_CK CHECK (LINE_STATUS IN ('OPEN','CLOSED','CANCELLED'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_SCHEDULES (
    SCHEDULE_ID            NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    PO_LINE_ID             NUMBER NOT NULL REFERENCES RR_PO_LINES(PO_LINE_ID),
    PO_HEADER_ID           NUMBER NOT NULL,
    SCHEDULE_NUM           NUMBER NOT NULL,
    SHIP_TO_LOCATION_ID    NUMBER,
    NEED_BY_DATE           DATE   NOT NULL,
    PROMISED_DATE          DATE,
    QUANTITY               NUMBER,
    AMOUNT                 NUMBER NOT NULL,
    QUANTITY_RECEIVED      NUMBER DEFAULT 0 NOT NULL,
    AMOUNT_RECEIVED        NUMBER DEFAULT 0 NOT NULL,
    QUANTITY_BILLED        NUMBER DEFAULT 0 NOT NULL,
    AMOUNT_BILLED          NUMBER DEFAULT 0 NOT NULL,
    QUANTITY_CANCELLED     NUMBER DEFAULT 0 NOT NULL,
    AMOUNT_CANCELLED       NUMBER DEFAULT 0 NOT NULL,
    MATCH_LEVEL            VARCHAR2(10),
    ACCRUE_AT_RECEIPT_FLAG VARCHAR2(1),
    OVER_RECEIPT_TOL_PCT   NUMBER(5,2),
    OVER_RECEIPT_ACTION    VARCHAR2(10),
    INV_QTY_TOL_PCT        NUMBER(5,2),
    INV_PRICE_TOL_PCT      NUMBER(5,2),
    RCV_CLOSE_TOL_PCT      NUMBER(5,2),
    INV_CLOSE_TOL_PCT      NUMBER(5,2),
    TAX_CODE               VARCHAR2(50),
    CLOSURE_STATUS         VARCHAR2(25) DEFAULT 'OPEN' NOT NULL,
    MANUAL_CLOSE_FLAG      VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    CANCELLED_FLAG         VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_S_CS_CK CHECK (CLOSURE_STATUS IN ('OPEN','CLOSED_FOR_RECEIVING','CLOSED_FOR_INVOICING','CLOSED','FINALLY_CLOSED'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_DISTRIBUTIONS (
    DISTRIBUTION_ID        NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    SCHEDULE_ID            NUMBER NOT NULL REFERENCES RR_PO_SCHEDULES(SCHEDULE_ID),
    PO_LINE_ID             NUMBER NOT NULL,
    PO_HEADER_ID           NUMBER NOT NULL,
    DIST_NUM               NUMBER NOT NULL,
    PERCENT                NUMBER(7,4) DEFAULT 100 NOT NULL,
    QUANTITY_ORDERED       NUMBER,
    AMOUNT_ORDERED         NUMBER NOT NULL,
    QUANTITY_DELIVERED     NUMBER DEFAULT 0 NOT NULL,
    AMOUNT_DELIVERED       NUMBER DEFAULT 0 NOT NULL,
    QUANTITY_BILLED        NUMBER DEFAULT 0 NOT NULL,
    AMOUNT_BILLED          NUMBER DEFAULT 0 NOT NULL,
    QUANTITY_CANCELLED     NUMBER DEFAULT 0 NOT NULL,
    AMOUNT_CANCELLED       NUMBER DEFAULT 0 NOT NULL,
    CHARGE_ACCOUNT         VARCHAR2(200) NOT NULL,
    ACCRUAL_ACCOUNT        VARCHAR2(200),
    VARIANCE_ACCOUNT       VARCHAR2(200),
    RATE                   NUMBER DEFAULT 1 NOT NULL,
    BUDGET_DATE            DATE,
    REQ_DISTRIBUTION_ID    NUMBER,
    REQUESTER_USER         VARCHAR2(150),
    DELIVER_TO_LOCATION_ID NUMBER,
    ACCRUED_AMOUNT_FUNC    NUMBER DEFAULT 0 NOT NULL,
    ENCUMBERED_AMOUNT      NUMBER,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_REVISIONS (
    REVISION_ID     NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    PO_HEADER_ID    NUMBER NOT NULL,
    REVISION_NUM    NUMBER NOT NULL,
    SNAPSHOT_JSON   CLOB,
    CHANGE_ORDER_ID NUMBER,
    CHANGE_SUMMARY  VARCHAR2(4000),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_REVISIONS_UK UNIQUE (PO_HEADER_ID, REVISION_NUM)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_CHANGE_ORDERS (
    CHANGE_ORDER_ID     NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    PO_HEADER_ID        NUMBER        NOT NULL,
    CO_NUMBER           VARCHAR2(60)  NOT NULL,
    FROM_REVISION       NUMBER        NOT NULL,
    STATUS              VARCHAR2(20) DEFAULT 'PENDING_APPROVAL' NOT NULL,
    REASON              VARCHAR2(1000) NOT NULL,
    CHANGES_JSON        CLOB          NOT NULL,
    CHANGE_SUMMARY      VARCHAR2(4000),
    AMOUNT_DELTA_FUNC   NUMBER DEFAULT 0 NOT NULL,
    APPROVAL_REQUEST_ID NUMBER,
    APPLIED_DATE        DATE,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_CO_ST_CK CHECK (STATUS IN ('DRAFT','PENDING_APPROVAL','APPLIED','REJECTED','CANCELLED'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

-- ── RECEIVING ────────────────────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_RCV_HEADERS (
    RECEIPT_HEADER_ID NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    RECEIPT_NUMBER    VARCHAR2(40) NOT NULL,
    BUSINESS_UNIT_ID  NUMBER       NOT NULL,
    SUPPLIER_ID       NUMBER       NOT NULL,
    SUPPLIER_SITE_ID  NUMBER       NOT NULL,
    RECEIPT_DATE      DATE         NOT NULL,
    DELIVERY_NOTE_NUM VARCHAR2(60),
    COMMENTS          VARCHAR2(1000),
    RECEIVED_BY       VARCHAR2(150) NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_RCV_H_UK UNIQUE (BUSINESS_UNIT_ID, RECEIPT_NUMBER)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_RCV_TRANSACTIONS (
    RCV_TRANSACTION_ID    NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    RECEIPT_HEADER_ID     NUMBER       NOT NULL REFERENCES RR_PO_RCV_HEADERS(RECEIPT_HEADER_ID),
    TRANSACTION_TYPE      VARCHAR2(20) NOT NULL,
    PARENT_TRANSACTION_ID NUMBER,
    TRANSACTION_DATE      DATE         NOT NULL,
    PO_HEADER_ID          NUMBER       NOT NULL,
    PO_LINE_ID            NUMBER       NOT NULL,
    SCHEDULE_ID           NUMBER       NOT NULL,
    QUANTITY              NUMBER,
    UOM_CODE              VARCHAR2(10),
    AMOUNT                NUMBER       NOT NULL,
    CURRENCY_CODE         VARCHAR2(15) NOT NULL,
    RATE                  NUMBER       NOT NULL,
    AMOUNT_FUNC           NUMBER       NOT NULL,
    REASON_CODE           VARCHAR2(30),
    COMMENTS              VARCHAR2(1000),
    ACCOUNTING_STATUS     VARCHAR2(15) NOT NULL,
    SLA_HEADER_ID         NUMBER,
    GL_BATCH_ID           NUMBER,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_RCV_T_TYPE_CK CHECK (TRANSACTION_TYPE IN ('RECEIVE','RETURN_TO_SUPPLIER','CORRECT')),
    CONSTRAINT RR_PO_RCV_T_ACC_CK CHECK (ACCOUNTING_STATUS IN ('UNACCOUNTED','ACCOUNTED','NOT_REQUIRED'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_RCV_DISTRIBUTIONS (
    RCV_DIST_ID        NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    RCV_TRANSACTION_ID NUMBER NOT NULL REFERENCES RR_PO_RCV_TRANSACTIONS(RCV_TRANSACTION_ID),
    DISTRIBUTION_ID    NUMBER NOT NULL REFERENCES RR_PO_DISTRIBUTIONS(DISTRIBUTION_ID),
    QUANTITY           NUMBER,
    AMOUNT             NUMBER NOT NULL,
    AMOUNT_FUNC        NUMBER NOT NULL,
    CHARGE_ACCOUNT     VARCHAR2(200) NOT NULL,
    ACCRUAL_ACCOUNT    VARCHAR2(200),
    QUANTITY_BILLED    NUMBER DEFAULT 0 NOT NULL,
    AMOUNT_BILLED      NUMBER DEFAULT 0 NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

-- ── ACCRUALS ─────────────────────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_ACCRUAL_RUNS (
    RUN_ID               NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    BUSINESS_UNIT_ID     NUMBER       NOT NULL,
    PERIOD_NAME          VARCHAR2(30) NOT NULL,
    ACCRUAL_DATE         DATE         NOT NULL,
    REVERSAL_DATE        DATE         NOT NULL,
    STATUS               VARCHAR2(15) DEFAULT 'DRAFT' NOT NULL,
    TOTAL_AMOUNT_FUNC    NUMBER DEFAULT 0 NOT NULL,
    SLA_HEADER_ID        NUMBER,
    GL_BATCH_ID          NUMBER,
    REVERSAL_GL_BATCH_ID NUMBER,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100),
    CONSTRAINT RR_PO_ACR_RUN_ST_CK CHECK (STATUS IN ('DRAFT','POSTED','CANCELLED'))
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_ACCRUAL_LINES (
    ACCRUAL_LINE_ID NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    RUN_ID          NUMBER NOT NULL REFERENCES RR_PO_ACCRUAL_RUNS(RUN_ID),
    DISTRIBUTION_ID NUMBER NOT NULL,
    QUANTITY        NUMBER,
    AMOUNT_FUNC     NUMBER NOT NULL,
    CHARGE_ACCOUNT  VARCHAR2(200) NOT NULL,
    ACCRUAL_ACCOUNT VARCHAR2(200) NOT NULL,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_ACCRUAL_WRITE_OFFS (
    WRITE_OFF_ID      NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    DISTRIBUTION_ID   NUMBER NOT NULL,
    AMOUNT_FUNC       NUMBER NOT NULL,
    WRITE_OFF_ACCOUNT VARCHAR2(200) NOT NULL,
    ACCRUAL_ACCOUNT   VARCHAR2(200) NOT NULL,
    WRITE_OFF_DATE    DATE NOT NULL,
    REASON            VARCHAR2(1000) NOT NULL,
    ACCOUNTING_STATUS VARCHAR2(15) DEFAULT 'UNACCOUNTED' NOT NULL,
    SLA_HEADER_ID     NUMBER,
    GL_BATCH_ID       NUMBER,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

-- ── CROSS-CUTTING ────────────────────────────────────────────────────────────
BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_ACTION_HISTORY (
    HISTORY_ID  NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    ENTITY_TYPE VARCHAR2(10)  NOT NULL,
    ENTITY_ID   NUMBER        NOT NULL,
    ACTION      VARCHAR2(40)  NOT NULL,
    FROM_STATUS VARCHAR2(30),
    TO_STATUS   VARCHAR2(30),
    ACTION_BY   VARCHAR2(150),
    ACTION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMMENTS    VARCHAR2(2000),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_PROC_REGISTRY (
    PROC_NAME    VARCHAR2(128) PRIMARY KEY,
    PARAMS_CSV   VARCHAR2(2000),
    CLOB_PARAMS  VARCHAR2(500),
    ENABLED_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DESCRIPTION  VARCHAR2(400),
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PO_EXEC_LOG (
    LOG_ID      NUMBER DEFAULT RR_PO_SEQ.NEXTVAL PRIMARY KEY,
    USER_NAME   VARCHAR2(150),
    PROC_NAME   VARCHAR2(128),
    PARAMS_CLOB CLOB,
    STATUS      VARCHAR2(1),
    MESSAGE     VARCHAR2(4000),
    RESULT_ID   NUMBER,
    ELAPSED_MS  NUMBER,
    CREATED_BY VARCHAR2(150), CREATION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150), LAST_UPDATE_DATE TIMESTAMP, LAST_UPDATE_LOGIN VARCHAR2(100)
)]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2275, -1408) THEN RAISE; END IF; END;
/

-- ── INDEXES ──────────────────────────────────────────────────────────────────
DECLARE
    -- local helper: still part of the anonymous block, so role privileges apply
    PROCEDURE RR_PO_DDL (p_sql IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
    END;
BEGIN
    RR_PO_DDL('CREATE INDEX RR_PO_REQ_L_HDR_IX   ON RR_PO_REQ_LINES (REQ_HEADER_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_REQ_L_ST_IX    ON RR_PO_REQ_LINES (LINE_STATUS, BUYER_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_REQ_D_LINE_IX  ON RR_PO_REQ_DISTRIBUTIONS (REQ_LINE_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_H_SUP_IX       ON RR_PO_HEADERS (SUPPLIER_ID, SUPPLIER_SITE_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_H_ST_IX        ON RR_PO_HEADERS (BUSINESS_UNIT_ID, DOCUMENT_STATUS, CLOSURE_STATUS)');
    RR_PO_DDL('CREATE INDEX RR_PO_L_HDR_IX       ON RR_PO_LINES (PO_HEADER_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_S_LINE_IX      ON RR_PO_SCHEDULES (PO_LINE_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_S_HDR_IX       ON RR_PO_SCHEDULES (PO_HEADER_ID, CLOSURE_STATUS)');
    RR_PO_DDL('CREATE INDEX RR_PO_D_SCH_IX       ON RR_PO_DISTRIBUTIONS (SCHEDULE_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_D_HDR_IX       ON RR_PO_DISTRIBUTIONS (PO_HEADER_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_RCV_T_SCH_IX   ON RR_PO_RCV_TRANSACTIONS (SCHEDULE_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_RCV_T_ACC_IX   ON RR_PO_RCV_TRANSACTIONS (ACCOUNTING_STATUS)');
    RR_PO_DDL('CREATE INDEX RR_PO_RCV_T_HDR_IX   ON RR_PO_RCV_TRANSACTIONS (RECEIPT_HEADER_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_RCV_D_TXN_IX   ON RR_PO_RCV_DISTRIBUTIONS (RCV_TRANSACTION_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_RCV_D_DIST_IX  ON RR_PO_RCV_DISTRIBUTIONS (DISTRIBUTION_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_HIST_ENT_IX    ON RR_PO_ACTION_HISTORY (ENTITY_TYPE, ENTITY_ID)');
    RR_PO_DDL('CREATE INDEX RR_PO_CO_HDR_IX      ON RR_PO_CHANGE_ORDERS (PO_HEADER_ID, STATUS)');
    RR_PO_DDL('CREATE INDEX RR_PO_ACR_L_RUN_IX   ON RR_PO_ACCRUAL_LINES (RUN_ID)');
END;
/

-- ── SEED: units of measure and starter categories (natural accounts left for finance) ──
MERGE INTO RR_PO_UOMS t
USING (SELECT 'EA' c, 'Each' n, 'COUNT' k FROM dual UNION ALL SELECT 'BOX','Box','COUNT' FROM dual
       UNION ALL SELECT 'PK','Pack','COUNT' FROM dual UNION ALL SELECT 'SET','Set','COUNT' FROM dual
       UNION ALL SELECT 'HR','Hour','TIME' FROM dual UNION ALL SELECT 'DAY','Day','TIME' FROM dual
       UNION ALL SELECT 'MON','Month','TIME' FROM dual UNION ALL SELECT 'YR','Year','TIME' FROM dual
       UNION ALL SELECT 'KG','Kilogram','WEIGHT' FROM dual UNION ALL SELECT 'LTR','Litre','VOLUME' FROM dual
       UNION ALL SELECT 'M','Metre','LENGTH' FROM dual UNION ALL SELECT 'LOT','Lot','COUNT' FROM dual) s
ON (t.UOM_CODE = s.c)
WHEN NOT MATCHED THEN INSERT (UOM_CODE, UOM_NAME, UOM_CLASS, CREATED_BY) VALUES (s.c, s.n, s.k, 'SEED');

MERGE INTO RR_PO_CATEGORIES t
USING (SELECT 'IT' c, 'Information Technology' n, NULL p, 'QUANTITY' lt, 'N' rq FROM dual
       UNION ALL SELECT 'IT.HARDWARE','IT Hardware','IT','QUANTITY','Y' FROM dual
       UNION ALL SELECT 'IT.SOFTWARE','Software & Licences','IT','QUANTITY','Y' FROM dual
       UNION ALL SELECT 'IT.ACCESSORIES','IT Accessories','IT','QUANTITY','Y' FROM dual
       UNION ALL SELECT 'OFFICE','Office',NULL,'QUANTITY','N' FROM dual
       UNION ALL SELECT 'OFFICE.STATIONERY','Stationery','OFFICE','QUANTITY','Y' FROM dual
       UNION ALL SELECT 'OFFICE.FURNITURE','Office Furniture','OFFICE','QUANTITY','Y' FROM dual
       UNION ALL SELECT 'FACILITIES','Facilities',NULL,'AMOUNT','N' FROM dual
       UNION ALL SELECT 'FACILITIES.MAINTENANCE','Repairs & Maintenance','FACILITIES','AMOUNT','Y' FROM dual
       UNION ALL SELECT 'FACILITIES.CLEANING','Cleaning Services','FACILITIES','AMOUNT','Y' FROM dual
       UNION ALL SELECT 'PROF','Professional Services',NULL,'AMOUNT','N' FROM dual
       UNION ALL SELECT 'PROF.CONSULTING','Consulting','PROF','AMOUNT','Y' FROM dual
       UNION ALL SELECT 'PROF.LEGAL','Legal Fees','PROF','AMOUNT','Y' FROM dual
       UNION ALL SELECT 'PROF.AUDIT','Audit Fees','PROF','AMOUNT','Y' FROM dual
       UNION ALL SELECT 'MKT','Marketing',NULL,'AMOUNT','N' FROM dual
       UNION ALL SELECT 'MKT.EVENTS','Events','MKT','AMOUNT','Y' FROM dual
       UNION ALL SELECT 'MKT.ADVERTISING','Advertising','MKT','AMOUNT','Y' FROM dual
       UNION ALL SELECT 'TRAVEL','Travel',NULL,'AMOUNT','Y' FROM dual
       UNION ALL SELECT 'RENT','Rent & Leases',NULL,'AMOUNT','Y' FROM dual) s
ON (t.CATEGORY_CODE = s.c)
WHEN NOT MATCHED THEN INSERT (CATEGORY_CODE, CATEGORY_NAME, DEFAULT_LINE_TYPE, REQUESTABLE_FLAG, CREATED_BY)
VALUES (s.c, s.n, NVL(s.lt, 'QUANTITY'), s.rq, 'SEED');

-- parents (second pass so children can find them)
UPDATE RR_PO_CATEGORIES c
SET    PARENT_CATEGORY_ID = (SELECT p.CATEGORY_ID FROM RR_PO_CATEGORIES p
                             WHERE p.CATEGORY_CODE = SUBSTR(c.CATEGORY_CODE, 1, INSTR(c.CATEGORY_CODE, '.') - 1))
WHERE  INSTR(c.CATEGORY_CODE, '.') > 0 AND c.PARENT_CATEGORY_ID IS NULL;
COMMIT;

-- Verify
SELECT table_name FROM user_tables WHERE table_name LIKE 'RR\_PO\_%' ESCAPE '\' ORDER BY 1;
