-- =============================================================================
-- Purchasing-RR (module PO) — 301: read views (one per screen)
--   Read through the existing guarded gateway POST ai/executequery
--   (appUser PURCHASING). Suppliers come from the existing RR_SUPPLIER_* tables.
-- Run after 300.
-- =============================================================================

-- Business units with their purchasing options
CREATE OR REPLACE VIEW RR_PO_V_BUSINESS_UNITS AS
SELECT bu.BUSINESS_UNIT_ID, bu.BUSINESS_UNIT_NAME, bu.COMPANY, bu.PRIMARY_LEDGER_ID,
       o.BU_OPTION_ID, o.FUNCTIONAL_CURRENCY, o.ACCRUE_AT_RECEIPT_FLAG, o.RECEIPT_ACCRUAL_ACCOUNT,
       o.REQUIRE_REQUISITION, o.PO_APPROVAL_REQUIRED, o.REQ_APPROVAL_REQUIRED,
       CASE WHEN o.BU_OPTION_ID IS NULL THEN 'N' ELSE 'Y' END AS OPTIONS_SET
FROM   RR_GL_BUSINESS_UNITS bu
LEFT   JOIN RR_PO_BU_OPTIONS o ON o.BUSINESS_UNIT_ID = bu.BUSINESS_UNIT_ID
WHERE  NVL(bu.ACTIVE_FLAG, 'Y') = 'Y';

-- Supplier sites usable for purchasing, one row per site and business unit
-- (assigned to the BU through RR_SUPPLIER_SITE_ASSIGNMENTS, or procurement BU of the site)
CREATE OR REPLACE VIEW RR_PO_V_SUPPLIER_SITES AS
WITH site_bu AS (
    SELECT a.SUPPLIER_SITE_ID, a.CLIENT_BU_ID AS BUSINESS_UNIT_ID,
           MAX(a.SHIP_TO_LOCATION_CODE) AS SHIP_TO_LOCATION_CODE,
           MAX(a.BILL_TO_LOCATION_CODE) AS BILL_TO_LOCATION_CODE
    FROM   RR_SUPPLIER_SITE_ASSIGNMENTS a
    WHERE  a.CLIENT_BU_ID IS NOT NULL
    AND    NVL(UPPER(a.STATUS), 'ACTIVE') <> 'INACTIVE'
    AND    (a.INACTIVE_DATE IS NULL OR a.INACTIVE_DATE > SYSDATE)
    GROUP  BY a.SUPPLIER_SITE_ID, a.CLIENT_BU_ID
    UNION
    SELECT s.SUPPLIER_SITE_ID, s.PROCUREMENT_BU_ID, NULL, NULL
    FROM   RR_SUPPLIER_SITES s
    WHERE  s.PROCUREMENT_BU_ID IS NOT NULL
)
SELECT m.SUPPLIER_ID, m.SUPPLIER AS SUPPLIER_NAME, m.SUPPLIER_NUMBER, m.TAX_REGISTRATION_NUMBER,
       s.SUPPLIER_SITE_ID, s.SUPPLIER_SITE AS SITE_NAME, s.SUPPLIER_SITE_CODE AS SITE_CODE,
       sb.BUSINESS_UNIT_ID, MAX(sb.SHIP_TO_LOCATION_CODE) AS SHIP_TO_LOCATION_CODE,
       MAX(sb.BILL_TO_LOCATION_CODE) AS BILL_TO_LOCATION_CODE,
       s.PAYMENT_TERMS, s.PAYMENT_TERMS_ID, s.PAY_SITE_FLAG,
       MAX(ad.FORMATTED_ADDRESS) AS ADDRESS,
       MAX(ad.CITY) AS CITY, MAX(ad.COUNTRY) AS COUNTRY,
       NVL(MAX(o.PURCHASING_HOLD_FLAG), 'N') AS PURCHASING_HOLD_FLAG, MAX(o.HOLD_REASON) AS HOLD_REASON,
       NVL(MAX(o.PO_COMMUNICATION), 'PRINT') AS PO_COMMUNICATION, MAX(o.PO_EMAIL) AS PO_EMAIL,
       MAX(o.DEFAULT_CURRENCY) AS DEFAULT_CURRENCY
FROM   RR_SUPPLIER_SITES s
JOIN   RR_SUPPLIER_MASTER m ON m.SUPPLIER_ID = s.SUPPLIER_ID
JOIN   site_bu sb           ON sb.SUPPLIER_SITE_ID = s.SUPPLIER_SITE_ID
LEFT   JOIN RR_SUPPLIER_ADDRESS ad ON ad.SUPPLIER_ID = s.SUPPLIER_ID AND ad.ADDRESS_NAME = s.ADDRESS_NAME
LEFT   JOIN RR_PO_SUPPLIER_SITE_OPTIONS o ON o.SUPPLIER_SITE_ID = s.SUPPLIER_SITE_ID
WHERE  NVL(s.PURCHASING_FLAG, 'N') = 'Y'
AND    (s.INACTIVE_DATE IS NULL OR s.INACTIVE_DATE > SYSDATE)
AND    NVL(UPPER(s.STATUS), 'ACTIVE') <> 'INACTIVE'
AND    NVL(UPPER(m.STATUS), 'ACTIVE') <> 'INACTIVE'
AND    (m.INACTIVE_DATE IS NULL OR CAST(m.INACTIVE_DATE AS DATE) > SYSDATE)
GROUP  BY m.SUPPLIER_ID, m.SUPPLIER, m.SUPPLIER_NUMBER, m.TAX_REGISTRATION_NUMBER,
          s.SUPPLIER_SITE_ID, s.SUPPLIER_SITE, s.SUPPLIER_SITE_CODE, sb.BUSINESS_UNIT_ID,
          s.PAYMENT_TERMS, s.PAYMENT_TERMS_ID, s.PAY_SITE_FLAG;

-- Category tree with the effective natural account (own or inherited)
CREATE OR REPLACE VIEW RR_PO_V_CATEGORIES AS
SELECT c.CATEGORY_ID, c.CATEGORY_CODE, c.CATEGORY_NAME, c.PARENT_CATEGORY_ID,
       p.CATEGORY_CODE AS PARENT_CODE, p.CATEGORY_NAME AS PARENT_NAME,
       c.DEFAULT_NATURAL_ACCOUNT,
       COALESCE(c.DEFAULT_NATURAL_ACCOUNT, p.DEFAULT_NATURAL_ACCOUNT) AS EFFECTIVE_NATURAL_ACCOUNT,
       c.DEFAULT_LINE_TYPE, c.DEFAULT_UOM, COALESCE(c.DEFAULT_TAX_CODE, p.DEFAULT_TAX_CODE) AS DEFAULT_TAX_CODE,
       c.RECEIPT_REQUIRED_FLAG, c.CAPEX_FLAG, c.REQUESTABLE_FLAG, c.STATUS,
       CASE WHEN p.CATEGORY_ID IS NULL THEN c.CATEGORY_NAME ELSE p.CATEGORY_NAME || ' › ' || c.CATEGORY_NAME END AS FULL_NAME
FROM   RR_PO_CATEGORIES c
LEFT   JOIN RR_PO_CATEGORIES p ON p.CATEGORY_ID = c.PARENT_CATEGORY_ID;

CREATE OR REPLACE VIEW RR_PO_V_EXPENSE_ITEMS AS
SELECT i.*, c.CATEGORY_CODE, c.CATEGORY_NAME, ss.SUPPLIER_NAME AS PREFERRED_SUPPLIER_NAME
FROM   RR_PO_EXPENSE_ITEMS i
JOIN   RR_PO_CATEGORIES c ON c.CATEGORY_ID = i.CATEGORY_ID
LEFT   JOIN (SELECT DISTINCT SUPPLIER_ID, SUPPLIER_NAME FROM RR_PO_V_SUPPLIER_SITES) ss
       ON ss.SUPPLIER_ID = i.PREFERRED_SUPPLIER_ID;

-- Requisitions
CREATE OR REPLACE VIEW RR_PO_V_REQUISITIONS AS
SELECT h.REQ_HEADER_ID, NVL(h.REQ_NUMBER, 'Draft #' || h.REQ_HEADER_ID) AS REQ_NUMBER, h.BUSINESS_UNIT_ID,
       bu.BUSINESS_UNIT_NAME, h.DESCRIPTION, h.JUSTIFICATION, h.PREPARER_USER, h.URGENT_FLAG, h.STATUS,
       h.FUNCTIONAL_CURRENCY, h.TOTAL_AMOUNT_FUNC, h.APPROVAL_REQUEST_ID, h.SUBMITTED_DATE, h.APPROVED_DATE,
       h.CREATION_DATE,
       (SELECT COUNT(*) FROM RR_PO_REQ_LINES l WHERE l.REQ_HEADER_ID = h.REQ_HEADER_ID) AS LINE_COUNT,
       (SELECT COUNT(*) FROM RR_PO_REQ_LINES l WHERE l.REQ_HEADER_ID = h.REQ_HEADER_ID AND l.LINE_STATUS = 'ON_PO') AS LINES_ON_PO
FROM   RR_PO_REQ_HEADERS h
LEFT   JOIN RR_GL_BUSINESS_UNITS bu ON bu.BUSINESS_UNIT_ID = h.BUSINESS_UNIT_ID;

CREATE OR REPLACE VIEW RR_PO_V_REQ_LINES AS
SELECT l.REQ_LINE_ID, l.REQ_HEADER_ID, NVL(h.REQ_NUMBER, 'Draft #' || h.REQ_HEADER_ID) AS REQ_NUMBER,
       h.BUSINESS_UNIT_ID, h.STATUS AS REQ_STATUS, h.DESCRIPTION AS REQ_DESCRIPTION, h.PREPARER_USER, h.URGENT_FLAG,
       h.APPROVED_DATE,
       l.LINE_NUM, l.LINE_TYPE, l.EXPENSE_ITEM_ID, i.ITEM_CODE, l.CATEGORY_ID, c.CATEGORY_CODE, c.CATEGORY_NAME,
       l.ITEM_DESCRIPTION, l.UOM_CODE, l.QUANTITY, l.UNIT_PRICE, l.AMOUNT, l.CURRENCY_CODE, l.RATE, l.AMOUNT_FUNC,
       l.TAX_CODE, l.NEED_BY_DATE, l.DELIVER_TO_LOCATION_ID, loc.LOCATION_NAME AS DELIVER_TO_NAME,
       l.REQUESTER_USER, l.SUGGESTED_SUPPLIER_ID, l.SUGGESTED_SUPPLIER_SITE_ID, l.SUGGESTED_SUPPLIER_NAME,
       sm.SUPPLIER AS SUGGESTED_SUPPLIER, l.SUPPLIER_ITEM_NUM, l.NOTE_TO_BUYER, l.BUYER_ID, b.USER_NAME AS BUYER_USER,
       l.LINE_STATUS, l.PO_LINE_ID, pl.PO_HEADER_ID, ph.PO_NUMBER,
       (SELECT MIN(d.CHARGE_ACCOUNT) FROM RR_PO_REQ_DISTRIBUTIONS d WHERE d.REQ_LINE_ID = l.REQ_LINE_ID) AS CHARGE_ACCOUNT,
       (SELECT COUNT(*) FROM RR_PO_REQ_DISTRIBUTIONS d WHERE d.REQ_LINE_ID = l.REQ_LINE_ID) AS DIST_COUNT
FROM   RR_PO_REQ_LINES l
JOIN   RR_PO_REQ_HEADERS h ON h.REQ_HEADER_ID = l.REQ_HEADER_ID
LEFT   JOIN RR_PO_CATEGORIES c   ON c.CATEGORY_ID = l.CATEGORY_ID
LEFT   JOIN RR_PO_EXPENSE_ITEMS i ON i.EXPENSE_ITEM_ID = l.EXPENSE_ITEM_ID
LEFT   JOIN RR_PO_LOCATIONS loc  ON loc.LOCATION_ID = l.DELIVER_TO_LOCATION_ID
LEFT   JOIN RR_SUPPLIER_MASTER sm ON sm.SUPPLIER_ID = l.SUGGESTED_SUPPLIER_ID
LEFT   JOIN RR_PO_BUYERS b       ON b.BUYER_ID = l.BUYER_ID
LEFT   JOIN RR_PO_LINES pl       ON pl.PO_LINE_ID = l.PO_LINE_ID
LEFT   JOIN RR_PO_HEADERS ph     ON ph.PO_HEADER_ID = pl.PO_HEADER_ID;

CREATE OR REPLACE VIEW RR_PO_V_REQ_DISTRIBUTIONS AS
SELECT d.*, l.REQ_HEADER_ID, l.LINE_NUM FROM RR_PO_REQ_DISTRIBUTIONS d JOIN RR_PO_REQ_LINES l ON l.REQ_LINE_ID = d.REQ_LINE_ID;

-- Purchase orders (header grid)
CREATE OR REPLACE VIEW RR_PO_V_ORDERS AS
SELECT h.PO_HEADER_ID, h.PO_NUMBER, h.REVISION_NUM, h.BUSINESS_UNIT_ID, bu.BUSINESS_UNIT_NAME, h.PO_TYPE, h.ORIGIN,
       h.SUPPLIER_ID, sm.SUPPLIER AS SUPPLIER_NAME, sm.SUPPLIER_NUMBER, sm.TAX_REGISTRATION_NUMBER,
       h.SUPPLIER_SITE_ID, ss.SUPPLIER_SITE AS SITE_NAME,
       (SELECT MAX(ad.FORMATTED_ADDRESS) FROM RR_SUPPLIER_ADDRESS ad
        WHERE ad.SUPPLIER_ID = ss.SUPPLIER_ID AND ad.ADDRESS_NAME = ss.ADDRESS_NAME) AS SUPPLIER_ADDRESS,
       h.SUPPLIER_CONTACT, h.BUYER_ID, h.BUYER_USER, h.CURRENCY_CODE, h.RATE_TYPE, h.RATE_DATE, h.RATE,
       h.PAYMENT_TERMS, h.SHIP_TO_LOCATION_ID, st.LOCATION_NAME AS SHIP_TO_NAME,
       h.BILL_TO_LOCATION_ID, bt.LOCATION_NAME AS BILL_TO_NAME, h.DESCRIPTION, h.NOTE_TO_SUPPLIER,
       h.DOCUMENT_STATUS, h.CLOSURE_STATUS, h.HOLD_FLAG, h.HOLD_REASON, h.TOTAL_AMOUNT, h.TOTAL_AMOUNT_FUNC,
       h.TOTAL_TAX_ESTIMATE, h.APPROVAL_REQUEST_ID, h.SUBMITTED_DATE, h.APPROVED_DATE, h.COMMUNICATED_DATE,
       h.AFTER_FACT_FLAG, h.CANCEL_REASON, h.CREATED_BY, h.CREATION_DATE,
       NVL(t.AMOUNT_RECEIVED, 0) AS AMOUNT_RECEIVED, NVL(t.AMOUNT_BILLED, 0) AS AMOUNT_BILLED,
       NVL(t.AMOUNT_CANCELLED, 0) AS AMOUNT_CANCELLED,
       NVL(t.AMOUNT_ORDERED, 0) - NVL(t.AMOUNT_CANCELLED, 0) - NVL(t.AMOUNT_RECEIVED, 0) AS AMOUNT_TO_RECEIVE,
       (SELECT COUNT(*) FROM RR_PO_CHANGE_ORDERS co WHERE co.PO_HEADER_ID = h.PO_HEADER_ID AND co.STATUS = 'PENDING_APPROVAL') AS PENDING_CHANGES
FROM   RR_PO_HEADERS h
LEFT   JOIN RR_GL_BUSINESS_UNITS bu ON bu.BUSINESS_UNIT_ID = h.BUSINESS_UNIT_ID
LEFT   JOIN RR_SUPPLIER_MASTER sm   ON sm.SUPPLIER_ID = h.SUPPLIER_ID
LEFT   JOIN RR_SUPPLIER_SITES ss    ON ss.SUPPLIER_SITE_ID = h.SUPPLIER_SITE_ID
LEFT   JOIN RR_PO_LOCATIONS st      ON st.LOCATION_ID = h.SHIP_TO_LOCATION_ID
LEFT   JOIN RR_PO_LOCATIONS bt      ON bt.LOCATION_ID = h.BILL_TO_LOCATION_ID
LEFT   JOIN (SELECT PO_HEADER_ID, SUM(AMOUNT) AMOUNT_ORDERED, SUM(AMOUNT_RECEIVED) AMOUNT_RECEIVED,
                    SUM(AMOUNT_BILLED) AMOUNT_BILLED, SUM(AMOUNT_CANCELLED) AMOUNT_CANCELLED
             FROM RR_PO_SCHEDULES GROUP BY PO_HEADER_ID) t ON t.PO_HEADER_ID = h.PO_HEADER_ID;

-- PO lines with their (first) schedule — the PO form grid
CREATE OR REPLACE VIEW RR_PO_V_ORDER_LINES AS
SELECT l.PO_LINE_ID, l.PO_HEADER_ID, h.PO_NUMBER, l.LINE_NUM, l.LINE_TYPE, l.EXPENSE_ITEM_ID, i.ITEM_CODE,
       l.CATEGORY_ID, c.CATEGORY_CODE, c.CATEGORY_NAME, l.ITEM_DESCRIPTION, l.SUPPLIER_ITEM_NUM, l.UOM_CODE,
       l.QUANTITY, l.UNIT_PRICE, l.AMOUNT, l.TAX_CODE, l.LINE_STATUS, l.CANCEL_REASON, l.CAPEX_FLAG, l.NOTE_TO_SUPPLIER,
       s.SCHEDULE_ID, s.SCHEDULE_NUM, s.SHIP_TO_LOCATION_ID, loc.LOCATION_NAME AS SHIP_TO_NAME, s.NEED_BY_DATE,
       s.PROMISED_DATE, s.QUANTITY_RECEIVED, s.AMOUNT_RECEIVED, s.QUANTITY_BILLED, s.AMOUNT_BILLED,
       s.QUANTITY_CANCELLED, s.AMOUNT_CANCELLED, s.MATCH_LEVEL, s.ACCRUE_AT_RECEIPT_FLAG, s.CLOSURE_STATUS,
       s.CANCELLED_FLAG,
       (SELECT MIN(d.CHARGE_ACCOUNT) FROM RR_PO_DISTRIBUTIONS d WHERE d.SCHEDULE_ID = s.SCHEDULE_ID) AS CHARGE_ACCOUNT,
       (SELECT MIN(d.REQUESTER_USER) FROM RR_PO_DISTRIBUTIONS d WHERE d.SCHEDULE_ID = s.SCHEDULE_ID) AS REQUESTER_USER,
       (SELECT COUNT(*) FROM RR_PO_DISTRIBUTIONS d WHERE d.SCHEDULE_ID = s.SCHEDULE_ID) AS DIST_COUNT,
       (SELECT SUM(d.ACCRUED_AMOUNT_FUNC) FROM RR_PO_DISTRIBUTIONS d WHERE d.SCHEDULE_ID = s.SCHEDULE_ID) AS ACCRUED_AMOUNT_FUNC,
       (SELECT MIN(rl.REQ_HEADER_ID) FROM RR_PO_REQ_LINES rl WHERE rl.PO_LINE_ID = l.PO_LINE_ID) AS REQ_HEADER_ID,
       (SELECT LISTAGG(rl.REQ_LINE_ID, ',') WITHIN GROUP (ORDER BY rl.REQ_LINE_ID) FROM RR_PO_REQ_LINES rl
         WHERE rl.PO_LINE_ID = l.PO_LINE_ID AND rl.LINE_STATUS = 'ON_PO') AS REQ_LINE_IDS
FROM   RR_PO_LINES l
JOIN   RR_PO_HEADERS h ON h.PO_HEADER_ID = l.PO_HEADER_ID
LEFT   JOIN RR_PO_SCHEDULES s ON s.PO_LINE_ID = l.PO_LINE_ID
                             AND s.SCHEDULE_NUM = (SELECT MIN(s2.SCHEDULE_NUM) FROM RR_PO_SCHEDULES s2 WHERE s2.PO_LINE_ID = l.PO_LINE_ID)
LEFT   JOIN RR_PO_CATEGORIES c    ON c.CATEGORY_ID = l.CATEGORY_ID
LEFT   JOIN RR_PO_EXPENSE_ITEMS i ON i.EXPENSE_ITEM_ID = l.EXPENSE_ITEM_ID
LEFT   JOIN RR_PO_LOCATIONS loc   ON loc.LOCATION_ID = s.SHIP_TO_LOCATION_ID;

CREATE OR REPLACE VIEW RR_PO_V_DISTRIBUTIONS AS
SELECT d.*, l.LINE_NUM, l.LINE_TYPE, l.ITEM_DESCRIPTION, l.UNIT_PRICE, h.PO_NUMBER, h.CURRENCY_CODE, h.BUSINESS_UNIT_ID
FROM   RR_PO_DISTRIBUTIONS d
JOIN   RR_PO_LINES l   ON l.PO_LINE_ID = d.PO_LINE_ID
JOIN   RR_PO_HEADERS h ON h.PO_HEADER_ID = d.PO_HEADER_ID;

-- Schedules that can be received now
CREATE OR REPLACE VIEW RR_PO_V_OPEN_SCHEDULES AS
SELECT s.SCHEDULE_ID, s.PO_LINE_ID, s.PO_HEADER_ID, h.PO_NUMBER, h.BUSINESS_UNIT_ID, h.SUPPLIER_ID, sm.SUPPLIER AS SUPPLIER_NAME,
       h.SUPPLIER_SITE_ID, ss.SUPPLIER_SITE AS SITE_NAME, h.CURRENCY_CODE, h.BUYER_USER,
       l.LINE_NUM, l.LINE_TYPE, l.ITEM_DESCRIPTION, l.UOM_CODE, l.UNIT_PRICE, c.CATEGORY_NAME,
       s.SCHEDULE_NUM, s.NEED_BY_DATE, s.SHIP_TO_LOCATION_ID, loc.LOCATION_NAME AS SHIP_TO_NAME,
       s.QUANTITY AS QUANTITY_ORDERED, s.AMOUNT AS AMOUNT_ORDERED, s.QUANTITY_RECEIVED, s.AMOUNT_RECEIVED,
       s.QUANTITY_CANCELLED, s.AMOUNT_CANCELLED,
       CASE WHEN l.LINE_TYPE = 'QUANTITY' THEN NVL(s.QUANTITY, 0) - s.QUANTITY_CANCELLED - s.QUANTITY_RECEIVED END AS QUANTITY_REMAINING,
       s.AMOUNT - s.AMOUNT_CANCELLED - s.AMOUNT_RECEIVED AS AMOUNT_REMAINING,
       s.OVER_RECEIPT_TOL_PCT, s.OVER_RECEIPT_ACTION, s.MATCH_LEVEL, s.CLOSURE_STATUS,
       (SELECT MIN(d.REQUESTER_USER) FROM RR_PO_DISTRIBUTIONS d WHERE d.SCHEDULE_ID = s.SCHEDULE_ID) AS REQUESTER_USER
FROM   RR_PO_SCHEDULES s
JOIN   RR_PO_LINES l   ON l.PO_LINE_ID = s.PO_LINE_ID
JOIN   RR_PO_HEADERS h ON h.PO_HEADER_ID = s.PO_HEADER_ID
LEFT   JOIN RR_SUPPLIER_MASTER sm ON sm.SUPPLIER_ID = h.SUPPLIER_ID
LEFT   JOIN RR_SUPPLIER_SITES ss  ON ss.SUPPLIER_SITE_ID = h.SUPPLIER_SITE_ID
LEFT   JOIN RR_PO_CATEGORIES c    ON c.CATEGORY_ID = l.CATEGORY_ID
LEFT   JOIN RR_PO_LOCATIONS loc   ON loc.LOCATION_ID = s.SHIP_TO_LOCATION_ID
WHERE  h.DOCUMENT_STATUS = 'APPROVED' AND h.HOLD_FLAG = 'N'
AND    s.CANCELLED_FLAG = 'N'
AND    s.CLOSURE_STATUS IN ('OPEN', 'CLOSED_FOR_INVOICING');

-- Receiving transactions (receipts, returns, corrections)
CREATE OR REPLACE VIEW RR_PO_V_RECEIPTS AS
SELECT t.RCV_TRANSACTION_ID, t.RECEIPT_HEADER_ID, r.RECEIPT_NUMBER, r.RECEIPT_DATE, r.DELIVERY_NOTE_NUM, r.RECEIVED_BY,
       r.BUSINESS_UNIT_ID, r.SUPPLIER_ID, sm.SUPPLIER AS SUPPLIER_NAME, r.SUPPLIER_SITE_ID,
       t.TRANSACTION_TYPE, t.PARENT_TRANSACTION_ID, t.TRANSACTION_DATE, t.PO_HEADER_ID, h.PO_NUMBER,
       t.PO_LINE_ID, l.LINE_NUM, l.LINE_TYPE, l.ITEM_DESCRIPTION, t.SCHEDULE_ID, t.QUANTITY, t.UOM_CODE, t.AMOUNT,
       t.CURRENCY_CODE, t.RATE, t.AMOUNT_FUNC, t.REASON_CODE, t.COMMENTS, t.ACCOUNTING_STATUS, t.SLA_HEADER_ID,
       t.GL_BATCH_ID, t.CREATED_BY, t.CREATION_DATE,
       -- for RECEIVE rows: what can still be returned (net of returns/corrections against it, and billed)
       CASE WHEN t.TRANSACTION_TYPE = 'RECEIVE' THEN
            NVL(t.QUANTITY, 0) + NVL((SELECT SUM(c.QUANTITY) FROM RR_PO_RCV_TRANSACTIONS c
                                       WHERE c.PARENT_TRANSACTION_ID = t.RCV_TRANSACTION_ID), 0)
            - NVL((SELECT SUM(rd.QUANTITY_BILLED) FROM RR_PO_RCV_DISTRIBUTIONS rd
                    WHERE rd.RCV_TRANSACTION_ID = t.RCV_TRANSACTION_ID), 0) END AS QUANTITY_RETURNABLE,
       CASE WHEN t.TRANSACTION_TYPE = 'RECEIVE' THEN
            t.AMOUNT + NVL((SELECT SUM(c.AMOUNT) FROM RR_PO_RCV_TRANSACTIONS c
                             WHERE c.PARENT_TRANSACTION_ID = t.RCV_TRANSACTION_ID), 0)
            - NVL((SELECT SUM(rd.AMOUNT_BILLED) FROM RR_PO_RCV_DISTRIBUTIONS rd
                    WHERE rd.RCV_TRANSACTION_ID = t.RCV_TRANSACTION_ID), 0) END AS AMOUNT_RETURNABLE
FROM   RR_PO_RCV_TRANSACTIONS t
JOIN   RR_PO_RCV_HEADERS r ON r.RECEIPT_HEADER_ID = t.RECEIPT_HEADER_ID
JOIN   RR_PO_HEADERS h     ON h.PO_HEADER_ID = t.PO_HEADER_ID
JOIN   RR_PO_LINES l       ON l.PO_LINE_ID = t.PO_LINE_ID
LEFT   JOIN RR_SUPPLIER_MASTER sm ON sm.SUPPLIER_ID = r.SUPPLIER_ID;

-- Accounting lines for receiving transactions (Dr/Cr per receipt distribution)
-- RECEIVE / positive CORRECT: Dr charge, Cr accrual; RETURN / negative CORRECT: reversed by sign
CREATE OR REPLACE VIEW RR_PO_V_RCV_ACCOUNTING AS
SELECT t.RCV_TRANSACTION_ID, t.TRANSACTION_TYPE, t.TRANSACTION_DATE, r.RECEIPT_NUMBER, r.BUSINESS_UNIT_ID,
       bu.BUSINESS_UNIT_NAME, h.PO_NUMBER, l.ITEM_DESCRIPTION, t.CURRENCY_CODE, t.RATE, t.ACCOUNTING_STATUS,
       rd.RCV_DIST_ID, rd.DISTRIBUTION_ID, rd.CHARGE_ACCOUNT, rd.ACCRUAL_ACCOUNT, rd.AMOUNT, rd.AMOUNT_FUNC
FROM   RR_PO_RCV_TRANSACTIONS t
JOIN   RR_PO_RCV_HEADERS r      ON r.RECEIPT_HEADER_ID = t.RECEIPT_HEADER_ID
JOIN   RR_PO_RCV_DISTRIBUTIONS rd ON rd.RCV_TRANSACTION_ID = t.RCV_TRANSACTION_ID
JOIN   RR_PO_HEADERS h          ON h.PO_HEADER_ID = t.PO_HEADER_ID
JOIN   RR_PO_LINES l            ON l.PO_LINE_ID = t.PO_LINE_ID
LEFT   JOIN RR_GL_BUSINESS_UNITS bu ON bu.BUSINESS_UNIT_ID = r.BUSINESS_UNIT_ID;

-- Uninvoiced receipts (GRNI sub-ledger) per distribution
CREATE OR REPLACE VIEW RR_PO_V_UNINVOICED AS
SELECT d.DISTRIBUTION_ID, d.PO_HEADER_ID, h.PO_NUMBER, h.BUSINESS_UNIT_ID, bu.BUSINESS_UNIT_NAME,
       h.SUPPLIER_ID, sm.SUPPLIER AS SUPPLIER_NAME, l.LINE_NUM, l.LINE_TYPE, l.ITEM_DESCRIPTION, l.UNIT_PRICE,
       h.CURRENCY_CODE, d.RATE, d.CHARGE_ACCOUNT, d.ACCRUAL_ACCOUNT, s.ACCRUE_AT_RECEIPT_FLAG, s.CLOSURE_STATUS,
       d.QUANTITY_DELIVERED, d.QUANTITY_BILLED, d.AMOUNT_DELIVERED, d.AMOUNT_BILLED,
       d.AMOUNT_DELIVERED - d.AMOUNT_BILLED AS AMOUNT_UNBILLED,
       ROUND((d.AMOUNT_DELIVERED - d.AMOUNT_BILLED) * d.RATE, 2) AS AMOUNT_UNBILLED_FUNC,
       d.ACCRUED_AMOUNT_FUNC,
       (SELECT MAX(t.TRANSACTION_DATE) FROM RR_PO_RCV_TRANSACTIONS t WHERE t.SCHEDULE_ID = s.SCHEDULE_ID) AS LAST_RECEIPT_DATE
FROM   RR_PO_DISTRIBUTIONS d
JOIN   RR_PO_SCHEDULES s ON s.SCHEDULE_ID = d.SCHEDULE_ID
JOIN   RR_PO_LINES l     ON l.PO_LINE_ID = d.PO_LINE_ID
JOIN   RR_PO_HEADERS h   ON h.PO_HEADER_ID = d.PO_HEADER_ID
LEFT   JOIN RR_GL_BUSINESS_UNITS bu ON bu.BUSINESS_UNIT_ID = h.BUSINESS_UNIT_ID
LEFT   JOIN RR_SUPPLIER_MASTER sm  ON sm.SUPPLIER_ID = h.SUPPLIER_ID
WHERE  d.AMOUNT_DELIVERED - d.AMOUNT_BILLED <> 0 OR d.ACCRUED_AMOUNT_FUNC <> 0;

CREATE OR REPLACE VIEW RR_PO_V_ACCRUAL_RUNS AS
SELECT r.*, bu.BUSINESS_UNIT_NAME,
       (SELECT COUNT(*) FROM RR_PO_ACCRUAL_LINES al WHERE al.RUN_ID = r.RUN_ID) AS LINE_COUNT
FROM   RR_PO_ACCRUAL_RUNS r LEFT JOIN RR_GL_BUSINESS_UNITS bu ON bu.BUSINESS_UNIT_ID = r.BUSINESS_UNIT_ID;

CREATE OR REPLACE VIEW RR_PO_V_ACCRUAL_LINES AS
SELECT al.*, d.PO_HEADER_ID, h.PO_NUMBER, l.LINE_NUM, l.ITEM_DESCRIPTION, sm.SUPPLIER AS SUPPLIER_NAME
FROM   RR_PO_ACCRUAL_LINES al
JOIN   RR_PO_DISTRIBUTIONS d ON d.DISTRIBUTION_ID = al.DISTRIBUTION_ID
JOIN   RR_PO_LINES l         ON l.PO_LINE_ID = d.PO_LINE_ID
JOIN   RR_PO_HEADERS h       ON h.PO_HEADER_ID = d.PO_HEADER_ID
LEFT   JOIN RR_SUPPLIER_MASTER sm ON sm.SUPPLIER_ID = h.SUPPLIER_ID;

CREATE OR REPLACE VIEW RR_PO_V_WRITE_OFFS AS
SELECT w.*, d.PO_HEADER_ID, h.PO_NUMBER, h.BUSINESS_UNIT_ID, h.CURRENCY_CODE, l.ITEM_DESCRIPTION
FROM   RR_PO_ACCRUAL_WRITE_OFFS w
JOIN   RR_PO_DISTRIBUTIONS d ON d.DISTRIBUTION_ID = w.DISTRIBUTION_ID
JOIN   RR_PO_LINES l         ON l.PO_LINE_ID = d.PO_LINE_ID
JOIN   RR_PO_HEADERS h       ON h.PO_HEADER_ID = d.PO_HEADER_ID;

CREATE OR REPLACE VIEW RR_PO_V_CHANGE_ORDERS AS
SELECT co.CHANGE_ORDER_ID, co.PO_HEADER_ID, co.CO_NUMBER, co.FROM_REVISION, co.STATUS, co.REASON, co.CHANGE_SUMMARY,
       co.AMOUNT_DELTA_FUNC, co.APPROVAL_REQUEST_ID, co.APPLIED_DATE, co.CREATED_BY, co.CREATION_DATE,
       CAST(SUBSTR(co.CHANGES_JSON, 1, 3900) AS VARCHAR2(3900)) AS CHANGES_TEXT,
       h.PO_NUMBER, h.BUSINESS_UNIT_ID, h.CURRENCY_CODE, h.REVISION_NUM AS CURRENT_REVISION
FROM   RR_PO_CHANGE_ORDERS co JOIN RR_PO_HEADERS h ON h.PO_HEADER_ID = co.PO_HEADER_ID;

CREATE OR REPLACE VIEW RR_PO_V_REVISIONS AS
SELECT REVISION_ID, PO_HEADER_ID, REVISION_NUM, CHANGE_ORDER_ID, CHANGE_SUMMARY, CREATED_BY, CREATION_DATE
FROM   RR_PO_REVISIONS;

CREATE OR REPLACE VIEW RR_PO_V_HISTORY AS
SELECT HISTORY_ID, ENTITY_TYPE, ENTITY_ID, ACTION, FROM_STATUS, TO_STATUS, ACTION_BY, ACTION_DATE, COMMENTS
FROM   RR_PO_ACTION_HISTORY;

-- Procurement approval requests (existing approval engine)
CREATE OR REPLACE VIEW RR_PO_V_APPROVALS AS
SELECT r.REQUEST_ID, r.TRANSACTION_TYPE, r.TRANSACTION_ID, r.TRANSACTION_REF, r.AMOUNT, r.CURRENCY, r.DESCRIPTION,
       r.REQUESTED_BY_NAME, r.REQUESTED_DATE, r.STATUS, r.RULE_ID, ru.RULE_NAME,
       u.FULL_NAME AS CURRENT_APPROVER, u.EMAIL AS CURRENT_APPROVER_EMAIL
FROM   RR_APPROVAL_REQUESTS r
LEFT   JOIN RR_APPROVAL_RULES ru ON ru.RULE_ID = r.RULE_ID
LEFT   JOIN RR_APPROVAL_USERS u  ON u.USER_ID = r.CURRENT_APPROVER_ID
WHERE  r.MODULE = 'PROCUREMENT';

-- Spend from receipts (until AP invoices are linked): by month, category, supplier, cost centre account
CREATE OR REPLACE VIEW RR_PO_V_SPEND AS
SELECT h.BUSINESS_UNIT_ID, TRUNC(t.TRANSACTION_DATE, 'MM') AS SPEND_MONTH, h.SUPPLIER_ID, sm.SUPPLIER AS SUPPLIER_NAME,
       c.CATEGORY_CODE, c.CATEGORY_NAME, rd.CHARGE_ACCOUNT, SUM(rd.AMOUNT_FUNC) AS AMOUNT_FUNC
FROM   RR_PO_RCV_DISTRIBUTIONS rd
JOIN   RR_PO_RCV_TRANSACTIONS t ON t.RCV_TRANSACTION_ID = rd.RCV_TRANSACTION_ID
JOIN   RR_PO_HEADERS h          ON h.PO_HEADER_ID = t.PO_HEADER_ID
JOIN   RR_PO_LINES l            ON l.PO_LINE_ID = t.PO_LINE_ID
LEFT   JOIN RR_PO_CATEGORIES c  ON c.CATEGORY_ID = l.CATEGORY_ID
LEFT   JOIN RR_SUPPLIER_MASTER sm ON sm.SUPPLIER_ID = h.SUPPLIER_ID
GROUP  BY h.BUSINESS_UNIT_ID, TRUNC(t.TRANSACTION_DATE, 'MM'), h.SUPPLIER_ID, sm.SUPPLIER, c.CATEGORY_CODE,
          c.CATEGORY_NAME, rd.CHARGE_ACCOUNT;

-- AI gateway access: when RR_AI_OBJECT_ACL runs in whitelist mode (any 'Y' row), the PO views
-- must be listed; in open mode nothing is added (adding 'Y' rows would switch it to whitelist mode).
DECLARE
    v_whitelist NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_whitelist FROM RR_AI_OBJECT_ACL WHERE ALLOWED_FLAG = 'Y';
    IF v_whitelist > 0 THEN
        FOR v IN (SELECT view_name FROM user_views WHERE view_name LIKE 'RR\_PO\_V\_%' ESCAPE '\'
                  UNION ALL SELECT table_name FROM user_tables WHERE table_name IN
                  ('RR_PO_CATEGORIES','RR_PO_LOCATIONS','RR_PO_UOMS','RR_PO_EXPENSE_ITEMS','RR_PO_BUYERS',
                   'RR_PO_REQUESTER_DEFAULTS','RR_PO_ACCOUNT_RULES','RR_PO_DOC_SEQUENCES','RR_PO_BU_OPTIONS',
                   'RR_PO_SUPPLIER_SITE_OPTIONS','RR_PO_REVISIONS','RR_PO_EXEC_LOG')) LOOP
            MERGE INTO RR_AI_OBJECT_ACL t USING (SELECT v.view_name n FROM dual) s ON (t.OBJECT_NAME = s.n)
            WHEN NOT MATCHED THEN INSERT (OBJECT_NAME, ALLOWED_FLAG) VALUES (s.n, 'Y');
        END LOOP;
        COMMIT;
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;   -- AI gateway not installed: nothing to do
END;
/

SELECT view_name FROM user_views WHERE view_name LIKE 'RR\_PO\_V\_%' ESCAPE '\' ORDER BY 1;
