-- =====================================================
-- AI Assistant — Training Recipes ("teach the assistant")
-- Table   : RR_AI_TRAINING
-- ORDS    : module 'reerp'
--             GET    ai/training       — list recipes (?all=Y includes disabled)
--             POST   ai/training       — create a recipe
--             PUT    ai/training/:id   — update a recipe (fields sent are updated)
--             DELETE ai/training/:id   — delete a recipe
--
-- A recipe teaches the in-app AI Assistant one action: a webservice call
-- (usually a page's search GET) with its parameters, labels and example
-- values. Recipes are loaded into the assistant's system prompt at runtime,
-- so anything taught here works immediately for every user — no code.
--
-- Recipes are captured two ways:
--   1. "Teach AI" button on a page after running a search (sends the exact
--      URL + parameter values that page used)
--   2. In chat: the assistant itself POSTs here via its user-approved
--      erp_api_write tool when the user says "learn this: ..."
-- =====================================================

-- DROP TABLE RR_AI_TRAINING CASCADE CONSTRAINTS;

CREATE TABLE RR_AI_TRAINING (
    RECIPE_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    RECIPE_NAME   VARCHAR2(200)  NOT NULL,
    DESCRIPTION   VARCHAR2(2000),                 -- when to use it: phrases, intent
    MODULE        VARCHAR2(30),                   -- GL / AP / AR / CASH / FA / PC ...
    METHOD        VARCHAR2(10)   DEFAULT 'GET' NOT NULL,
    URL_TEMPLATE  VARCHAR2(1000) NOT NULL,        -- path only, e.g. /cash/externaltransactions
    PARAMS_JSON   CLOB,                           -- [{"name","label","example","required","description"}]
    EXAMPLE_JSON  CLOB,                           -- the exact values captured at teach time
    APP_PATH      VARCHAR2(300),                  -- related app page (for navigate_to_page)
    ENABLED       VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
    CREATED_BY    VARCHAR2(240),
    CREATION_DATE TIMESTAMP      DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY  VARCHAR2(240),
    LAST_UPDATE_DATE TIMESTAMP,
    CONSTRAINT RR_AI_TRAINING_METHOD_CK  CHECK (METHOD IN ('GET','POST','PUT','DELETE','PATCH')),
    CONSTRAINT RR_AI_TRAINING_ENABLED_CK CHECK (ENABLED IN ('Y','N')),
    CONSTRAINT RR_AI_TRAINING_PARAMS_CK  CHECK (PARAMS_JSON  IS JSON),
    CONSTRAINT RR_AI_TRAINING_EXAMPLE_CK CHECK (EXAMPLE_JSON IS JSON)
);

COMMENT ON TABLE RR_AI_TRAINING IS
    'Taught recipes for the in-app AI Assistant: webservice calls with parameters, captured from pages or from chat';

-- =====================================================
-- ORDS: /ai/training  (GET list, POST create)
-- =====================================================
BEGIN
    ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ai/training');
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'ai/training',
        p_comments    => 'AI Assistant training recipes'
    );
    COMMIT;
END;
/

-- ── GET /ai/training ─────────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name => 'reerp',
        p_pattern     => 'ai/training',
        p_method      => 'GET',
        p_source_type => 'json/collection',
        p_comments    => 'List AI training recipes (?all=Y includes disabled)',
        p_source      => '
SELECT recipe_id                                  AS "recipeId",
       recipe_name                                AS "recipeName",
       description                                AS "description",
       module                                     AS "module",
       method                                     AS "method",
       url_template                               AS "urlTemplate",
       params_json                                AS "paramsJson",
       example_json                               AS "exampleJson",
       app_path                                   AS "appPath",
       enabled                                    AS "enabled",
       created_by                                 AS "createdBy",
       TO_CHAR(creation_date,   ''YYYY-MM-DD HH24:MI'') AS "createdAt",
       TO_CHAR(last_update_date,''YYYY-MM-DD HH24:MI'') AS "updatedAt"
FROM   rr_ai_training
WHERE  (NVL(:all, ''N'') = ''Y'' OR enabled = ''Y'')
ORDER  BY module, recipe_name'
    );
    COMMIT;
END;
/

-- ── POST /ai/training ────────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name   => 'reerp',
        p_pattern       => 'ai/training',
        p_method        => 'POST',
        p_source_type   => 'plsql/block',
        p_mimes_allowed => 'application/json',
        p_comments      => 'Create an AI training recipe',
        p_source        => '
DECLARE
    l_body     CLOB := :body_text;
    l_name     VARCHAR2(200);
    l_desc     VARCHAR2(2000);
    l_module   VARCHAR2(30);
    l_method   VARCHAR2(10);
    l_url      VARCHAR2(1000);
    l_params   CLOB;
    l_example  CLOB;
    l_apppath  VARCHAR2(300);
    l_by       VARCHAR2(240);
    l_id       NUMBER;
BEGIN
    APEX_JSON.PARSE(l_body);
    l_name    := APEX_JSON.GET_VARCHAR2(p_path => ''recipeName'');
    l_desc    := APEX_JSON.GET_VARCHAR2(p_path => ''description'');
    l_module  := UPPER(APEX_JSON.GET_VARCHAR2(p_path => ''module''));
    l_method  := UPPER(NVL(APEX_JSON.GET_VARCHAR2(p_path => ''method''), ''GET''));
    l_url     := APEX_JSON.GET_VARCHAR2(p_path => ''urlTemplate'');
    l_apppath := APEX_JSON.GET_VARCHAR2(p_path => ''appPath'');
    l_by      := NVL(APEX_JSON.GET_VARCHAR2(p_path => ''createdBy''), ''REERP'');

    -- params/example are sent as pre-stringified JSON strings
    BEGIN l_params  := APEX_JSON.GET_CLOB(p_path => ''paramsJson'');  EXCEPTION WHEN OTHERS THEN l_params  := APEX_JSON.GET_VARCHAR2(p_path => ''paramsJson'');  END;
    BEGIN l_example := APEX_JSON.GET_CLOB(p_path => ''exampleJson''); EXCEPTION WHEN OTHERS THEN l_example := APEX_JSON.GET_VARCHAR2(p_path => ''exampleJson''); END;

    IF l_name IS NULL OR l_url IS NULL THEN
        :status_code := 400;
        HTP.P(''{"success":false,"message":"recipeName and urlTemplate are required"}'');
        RETURN;
    END IF;
    IF SUBSTR(l_url, 1, 1) <> ''/'' THEN
        :status_code := 400;
        HTP.P(''{"success":false,"message":"urlTemplate must start with /"}'');
        RETURN;
    END IF;

    INSERT INTO rr_ai_training
        (recipe_name, description, module, method, url_template,
         params_json, example_json, app_path, enabled, created_by)
    VALUES
        (l_name, l_desc, l_module, l_method, l_url,
         l_params, l_example, l_apppath, ''Y'', l_by)
    RETURNING recipe_id INTO l_id;
    COMMIT;

    :status_code := 201;
    HTP.P(''{"success":true,"recipeId":'' || l_id || '',"message":"Recipe saved"}'');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P(''{"success":false,"message":"'' || REPLACE(SQLERRM, ''"'', '''''''') || ''"}'');
END;'
    );
    COMMIT;
END;
/

-- =====================================================
-- ORDS: /ai/training/:id  (PUT update, DELETE remove)
-- =====================================================
BEGIN
    ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ai/training/:id');
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'ai/training/:id',
        p_comments    => 'One AI training recipe'
    );
    COMMIT;
END;
/

-- ── PUT /ai/training/:id ─────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name   => 'reerp',
        p_pattern       => 'ai/training/:id',
        p_method        => 'PUT',
        p_source_type   => 'plsql/block',
        p_mimes_allowed => 'application/json',
        p_comments      => 'Update an AI training recipe (only fields present in the body change)',
        p_source        => '
DECLARE
    l_body    CLOB := :body_text;
    l_id      NUMBER := :id;
    l_count   NUMBER;
    l_params  CLOB;
    l_example CLOB;
BEGIN
    APEX_JSON.PARSE(l_body);

    SELECT COUNT(*) INTO l_count FROM rr_ai_training WHERE recipe_id = l_id;
    IF l_count = 0 THEN
        :status_code := 404;
        HTP.P(''{"success":false,"message":"Recipe '' || l_id || '' not found"}'');
        RETURN;
    END IF;

    BEGIN l_params  := APEX_JSON.GET_CLOB(p_path => ''paramsJson'');  EXCEPTION WHEN OTHERS THEN l_params  := APEX_JSON.GET_VARCHAR2(p_path => ''paramsJson'');  END;
    BEGIN l_example := APEX_JSON.GET_CLOB(p_path => ''exampleJson''); EXCEPTION WHEN OTHERS THEN l_example := APEX_JSON.GET_VARCHAR2(p_path => ''exampleJson''); END;

    UPDATE rr_ai_training
    SET    recipe_name  = NVL(APEX_JSON.GET_VARCHAR2(p_path => ''recipeName''), recipe_name),
           description  = NVL(APEX_JSON.GET_VARCHAR2(p_path => ''description''), description),
           module       = NVL(UPPER(APEX_JSON.GET_VARCHAR2(p_path => ''module'')), module),
           method       = NVL(UPPER(APEX_JSON.GET_VARCHAR2(p_path => ''method'')), method),
           url_template = NVL(APEX_JSON.GET_VARCHAR2(p_path => ''urlTemplate''), url_template),
           app_path     = NVL(APEX_JSON.GET_VARCHAR2(p_path => ''appPath''), app_path),
           enabled      = NVL(UPPER(APEX_JSON.GET_VARCHAR2(p_path => ''enabled'')), enabled),
           params_json  = NVL(l_params,  params_json),
           example_json = NVL(l_example, example_json),
           last_updated_by  = NVL(APEX_JSON.GET_VARCHAR2(p_path => ''updatedBy''), ''REERP''),
           last_update_date = SYSTIMESTAMP
    WHERE  recipe_id = l_id;
    COMMIT;

    HTP.P(''{"success":true,"recipeId":'' || l_id || '',"message":"Recipe updated"}'');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P(''{"success":false,"message":"'' || REPLACE(SQLERRM, ''"'', '''''''') || ''"}'');
END;'
    );
    COMMIT;
END;
/

-- ── DELETE /ai/training/:id ──────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name => 'reerp',
        p_pattern     => 'ai/training/:id',
        p_method      => 'DELETE',
        p_source_type => 'plsql/block',
        p_comments    => 'Delete an AI training recipe',
        p_source      => '
DECLARE
    l_id NUMBER := :id;
BEGIN
    DELETE FROM rr_ai_training WHERE recipe_id = l_id;
    IF SQL%ROWCOUNT = 0 THEN
        :status_code := 404;
        HTP.P(''{"success":false,"message":"Recipe '' || l_id || '' not found"}'');
        RETURN;
    END IF;
    COMMIT;
    HTP.P(''{"success":true,"message":"Recipe deleted"}'');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P(''{"success":false,"message":"'' || REPLACE(SQLERRM, ''"'', '''''''') || ''"}'');
END;'
    );
    COMMIT;
END;
/

-- =====================================================
-- Seed: the pilot recipe (external transactions search)
-- =====================================================
INSERT INTO rr_ai_training
    (recipe_name, description, module, method, url_template, params_json, example_json, app_path, created_by)
VALUES (
    'Search External Transactions',
    'Search / find / list external cash transactions. Use for questions like "search external transactions", "show unreconciled bank items", "external transactions for June".',
    'CASH',
    'GET',
    '/cash/externaltransactions',
    '[{"name":"bank_account","label":"Bank Account","required":false},
      {"name":"business_unit","label":"Business Unit","required":false},
      {"name":"status","label":"Status","required":false},
      {"name":"transaction_type","label":"Transaction Type","required":false},
      {"name":"transaction_number","label":"Transaction #","required":false},
      {"name":"reference","label":"Reference text","required":false},
      {"name":"currency_code","label":"Currency","required":false},
      {"name":"date_from","label":"Transaction date from (YYYY-MM-DD)","required":true},
      {"name":"date_to","label":"Transaction date to (YYYY-MM-DD)","required":true},
      {"name":"amount_from","label":"Min amount","required":false},
      {"name":"amount_to","label":"Max amount","required":false},
      {"name":"row_limit","label":"Row limit","example":"500","required":false}]',
    '{"date_from":"2026-06-01","date_to":"2026-06-30","business_unit":"BUIMERC CORP_DIFC_INVST","row_limit":"500"}',
    '/cash/external-transactions',
    'SEED'
);
COMMIT;

-- =====================================================
-- VERIFY
--   GET  {base}/ai/training            → seeded recipe listed
--   POST {base}/ai/training            → 201 with recipeId
--   PUT  {base}/ai/training/1  {"enabled":"N"}  → recipe hidden from GET
-- =====================================================
