-- =====================================================
-- Patch 130 — Dashboard Designer (company-shared dashboards)
--
--   Table:    RR_DASHBOARDS       — one row per dashboard, definition as JSON
--   Endpoints (module reerp):
--     GET    dashboards           — list (id, name, description, audit cols)
--     GET    dashboards/:id       — one dashboard incl. its JSON definition
--     POST   dashboards           — create  {name, description, definition, user}
--     PUT    dashboards/:id       — update  (fields sent are updated)
--     DELETE dashboards/:id       — delete
--
-- Dashboards are shared company-wide: every user sees every dashboard.
-- The definition JSON is owned by the app (widgets, layout, sources).
-- =====================================================

-- DROP TABLE RR_DASHBOARDS CASCADE CONSTRAINTS;

CREATE TABLE RR_DASHBOARDS (
    DASHBOARD_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME             VARCHAR2(200)  NOT NULL,
    DESCRIPTION      VARCHAR2(1000),
    DEFINITION       CLOB,                          -- {widgets:[...], layouts:{...}} JSON
    ENABLED          VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
    CREATED_BY       VARCHAR2(240),
    CREATION_DATE    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY  VARCHAR2(240),
    LAST_UPDATE_DATE TIMESTAMP,
    CONSTRAINT RR_DASHBOARDS_ENABLED_CK CHECK (ENABLED IN ('Y','N')),
    CONSTRAINT RR_DASHBOARDS_DEF_CK     CHECK (DEFINITION IS JSON)
);

COMMENT ON TABLE RR_DASHBOARDS IS
    'Company-shared user-designed dashboards (Dashboard Designer page); DEFINITION holds widgets/layout JSON';

-- ── templates ────────────────────────────────────────
BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'dashboards');
    ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'dashboards/:id');
    COMMIT;
END;
/

-- ── GET dashboards (list, no definitions — keep it light) ────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name => 'reerp',
        p_pattern     => 'dashboards',
        p_method      => 'GET',
        p_source_type => 'json/collection',
        p_comments    => 'List company dashboards',
        p_source      => '
SELECT dashboard_id                                   AS "dashboardId",
       name                                           AS "name",
       description                                    AS "description",
       created_by                                     AS "createdBy",
       TO_CHAR(creation_date,    ''YYYY-MM-DD HH24:MI'') AS "createdAt",
       last_updated_by                                AS "updatedBy",
       TO_CHAR(last_update_date, ''YYYY-MM-DD HH24:MI'') AS "updatedAt"
FROM   rr_dashboards
WHERE  enabled = ''Y''
ORDER  BY name'
    );
    COMMIT;
END;
/

-- ── GET dashboards/:id (with definition) ─────────────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name => 'reerp',
        p_pattern     => 'dashboards/:id',
        p_method      => 'GET',
        p_source_type => 'json/collection',
        p_comments    => 'One dashboard including its JSON definition',
        p_source      => '
SELECT dashboard_id  AS "dashboardId",
       name          AS "name",
       description   AS "description",
       definition    AS "definition",
       created_by    AS "createdBy",
       last_updated_by AS "updatedBy"
FROM   rr_dashboards
WHERE  dashboard_id = :id'
    );
    COMMIT;
END;
/

-- ── POST dashboards (create) ─────────────────────────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name   => 'reerp',
        p_pattern       => 'dashboards',
        p_method        => 'POST',
        p_source_type   => 'plsql/block',
        p_mimes_allowed => 'application/json',
        p_comments      => 'Create a dashboard',
        p_source        => '
DECLARE
    l_body CLOB := :body_text;
    l_name VARCHAR2(200);
    l_desc VARCHAR2(1000);
    l_def  CLOB;
    l_by   VARCHAR2(240);
    l_id   NUMBER;
BEGIN
    APEX_JSON.PARSE(l_body);
    l_name := APEX_JSON.GET_VARCHAR2(p_path => ''name'');
    l_desc := APEX_JSON.GET_VARCHAR2(p_path => ''description'');
    BEGIN l_def := APEX_JSON.GET_CLOB(p_path => ''definition''); EXCEPTION WHEN OTHERS THEN l_def := APEX_JSON.GET_VARCHAR2(p_path => ''definition''); END;
    l_by   := NVL(APEX_JSON.GET_VARCHAR2(p_path => ''user''), ''REERP'');
    IF l_name IS NULL THEN
        :status := 400;
        APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE(''success'', FALSE);
        APEX_JSON.WRITE(''message'', ''name is required''); APEX_JSON.CLOSE_OBJECT;
        RETURN;
    END IF;
    INSERT INTO rr_dashboards (name, description, definition, created_by)
    VALUES (l_name, l_desc, l_def, UPPER(l_by))
    RETURNING dashboard_id INTO l_id;
    COMMIT;
    :status := 201;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE(''success'', TRUE);
    APEX_JSON.WRITE(''dashboardId'', l_id);
    APEX_JSON.CLOSE_OBJECT;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status := 500;
    APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE(''success'', FALSE);
    APEX_JSON.WRITE(''message'', SQLERRM); APEX_JSON.CLOSE_OBJECT;
END;'
    );
    COMMIT;
END;
/

-- ── PUT dashboards/:id (update fields sent) ──────────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name   => 'reerp',
        p_pattern       => 'dashboards/:id',
        p_method        => 'PUT',
        p_source_type   => 'plsql/block',
        p_mimes_allowed => 'application/json',
        p_comments      => 'Update a dashboard (name/description/definition/enabled)',
        p_source        => '
DECLARE
    l_body CLOB := :body_text;
    l_name VARCHAR2(200);
    l_desc VARCHAR2(1000);
    l_def  CLOB;
    l_en   VARCHAR2(1);
    l_by   VARCHAR2(240);
BEGIN
    APEX_JSON.PARSE(l_body);
    l_name := APEX_JSON.GET_VARCHAR2(p_path => ''name'');
    l_desc := APEX_JSON.GET_VARCHAR2(p_path => ''description'');
    BEGIN l_def := APEX_JSON.GET_CLOB(p_path => ''definition''); EXCEPTION WHEN OTHERS THEN l_def := APEX_JSON.GET_VARCHAR2(p_path => ''definition''); END;
    l_en   := UPPER(APEX_JSON.GET_VARCHAR2(p_path => ''enabled''));
    l_by   := NVL(APEX_JSON.GET_VARCHAR2(p_path => ''user''), ''REERP'');
    UPDATE rr_dashboards
    SET    name             = NVL(l_name, name),
           description      = NVL(l_desc, description),
           definition       = NVL(l_def, definition),
           enabled          = CASE WHEN l_en IN (''Y'',''N'') THEN l_en ELSE enabled END,
           last_updated_by  = UPPER(l_by),
           last_update_date = SYSTIMESTAMP
    WHERE  dashboard_id = :id;
    IF SQL%ROWCOUNT = 0 THEN
        :status := 404;
        APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE(''success'', FALSE);
        APEX_JSON.WRITE(''message'', ''Dashboard not found''); APEX_JSON.CLOSE_OBJECT;
        RETURN;
    END IF;
    COMMIT;
    APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE(''success'', TRUE); APEX_JSON.CLOSE_OBJECT;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status := 500;
    APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE(''success'', FALSE);
    APEX_JSON.WRITE(''message'', SQLERRM); APEX_JSON.CLOSE_OBJECT;
END;'
    );
    COMMIT;
END;
/

-- ── DELETE dashboards/:id ────────────────────────────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name => 'reerp',
        p_pattern     => 'dashboards/:id',
        p_method      => 'DELETE',
        p_source_type => 'plsql/block',
        p_comments    => 'Delete a dashboard',
        p_source      => '
BEGIN
    DELETE FROM rr_dashboards WHERE dashboard_id = :id;
    COMMIT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE(''success'', TRUE);
    APEX_JSON.CLOSE_OBJECT;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status := 500;
    APEX_JSON.OPEN_OBJECT; APEX_JSON.WRITE(''success'', FALSE);
    APEX_JSON.WRITE(''message'', SQLERRM); APEX_JSON.CLOSE_OBJECT;
END;'
    );
    COMMIT;
END;
/
