-- ============================================================
-- Patch 154: RR_BU_ACCOUNTS_ASSIGNMENTS
--            Business Unit + account assignments per customer party
--            (Fusion-style customer account defaults: Receivables,
--             Revenue, Tax, ... per BU)
--
-- Party comes from RR_RAW_AR_HZ_PARTIES_DM (PARTY_ID).
-- One row per (PARTY_ID, BUSINESS_UNIT_NAME); each account column is a
-- full GL code combination whose company segment matches the BU's
-- company code (enforced by the UI account picker).
--
-- Endpoints:
--   GET  ar/buaccounts?party_id=...      -> { success, items:[...] }
--   POST ar/buaccounts                    -> insert  (first save)
--   PUT  ar/buaccounts/:assignmentId      -> update  (later saves)
--
-- HOW TO RUN: each statement separately in APEX SQL Commands, or the
-- whole file via SQL Workshop -> SQL Scripts.
-- ============================================================

-- ── 1. Table ───────────────────────────────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE RR_BU_ACCOUNTS_ASSIGNMENTS (
      ASSIGNMENT_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      PARTY_ID             NUMBER NOT NULL,
      PARTY_NAME           VARCHAR2(400),
      BUSINESS_UNIT_NAME   VARCHAR2(240) NOT NULL,
      COMPANY_CODE         VARCHAR2(30),
      RECEIVABLES_ACCOUNT  VARCHAR2(200),
      REVENUE_ACCOUNT      VARCHAR2(200),
      TAX_ACCOUNT          VARCHAR2(200),
      FREIGHT_ACCOUNT      VARCHAR2(200),
      UNBILLED_ACCOUNT     VARCHAR2(200),
      UNEARNED_ACCOUNT     VARCHAR2(200),
      CLEARING_ACCOUNT     VARCHAR2(200),
      STATUS               VARCHAR2(20) DEFAULT 'ACTIVE',
      CREATED_BY           VARCHAR2(150),
      CREATION_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
      LAST_UPDATED_BY      VARCHAR2(150),
      LAST_UPDATE_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP,
      CONSTRAINT RR_BU_ACCT_ASSIGN_UK UNIQUE (PARTY_ID, BUSINESS_UNIT_NAME)
    )]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE RR_BU_ACCOUNTS_ASSIGNMENTS IS
  'Customer (party) to Business Unit account assignments — Fusion-style AR account defaults. PARTY_ID references RR_RAW_AR_HZ_PARTIES_DM. One row per party per business unit; each *_ACCOUNT column holds a full GL code combination whose company segment equals COMPANY_CODE (the BU''s company).';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.PARTY_ID            IS 'Customer party id (RR_RAW_AR_HZ_PARTIES_DM.PARTY_ID)';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.BUSINESS_UNIT_NAME  IS 'Business unit the accounts apply to';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.COMPANY_CODE        IS 'Company segment value of the business unit';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.RECEIVABLES_ACCOUNT IS 'Receivables GL code combination';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.REVENUE_ACCOUNT     IS 'Revenue GL code combination';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.TAX_ACCOUNT         IS 'Tax GL code combination';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.FREIGHT_ACCOUNT     IS 'Freight GL code combination';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.UNBILLED_ACCOUNT    IS 'Unbilled receivable GL code combination';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.UNEARNED_ACCOUNT    IS 'Unearned revenue GL code combination';
COMMENT ON COLUMN RR_BU_ACCOUNTS_ASSIGNMENTS.CLEARING_ACCOUNT    IS 'AutoInvoice clearing GL code combination';

-- ── 2. GET ar/buaccounts?party_id= ─────────────────────────────────────────
BEGIN
    BEGIN
        ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ar/buaccounts');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ar/buaccounts');

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'ar/buaccounts',
        p_method         => 'GET',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_comments       => 'BU account assignments for a party',
        p_source         => q'[
DECLARE
    l_out   CLOB;
    l_len   NUMBER;
    l_pos   NUMBER := 1;
BEGIN
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('items');
    FOR r IN (SELECT * FROM RR_BU_ACCOUNTS_ASSIGNMENTS
               WHERE PARTY_ID = TO_NUMBER(:party_id)
               ORDER BY BUSINESS_UNIT_NAME) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('assignmentId',       r.ASSIGNMENT_ID);
        APEX_JSON.WRITE('partyId',            r.PARTY_ID);
        APEX_JSON.WRITE('partyName',          r.PARTY_NAME);
        APEX_JSON.WRITE('businessUnitName',   r.BUSINESS_UNIT_NAME);
        APEX_JSON.WRITE('companyCode',        r.COMPANY_CODE);
        APEX_JSON.WRITE('receivablesAccount', r.RECEIVABLES_ACCOUNT);
        APEX_JSON.WRITE('revenueAccount',     r.REVENUE_ACCOUNT);
        APEX_JSON.WRITE('taxAccount',         r.TAX_ACCOUNT);
        APEX_JSON.WRITE('freightAccount',     r.FREIGHT_ACCOUNT);
        APEX_JSON.WRITE('unbilledAccount',    r.UNBILLED_ACCOUNT);
        APEX_JSON.WRITE('unearnedAccount',    r.UNEARNED_ACCOUNT);
        APEX_JSON.WRITE('clearingAccount',    r.CLEARING_ACCOUNT);
        APEX_JSON.WRITE('status',             r.STATUS);
        APEX_JSON.WRITE('createdBy',          r.CREATED_BY);
        APEX_JSON.WRITE('creationDate',       TO_CHAR(r.CREATION_DATE, 'YYYY-MM-DD HH24:MI'));
        APEX_JSON.WRITE('lastUpdatedBy',      r.LAST_UPDATED_BY);
        APEX_JSON.WRITE('lastUpdateDate',     TO_CHAR(r.LAST_UPDATE_DATE, 'YYYY-MM-DD HH24:MI'));
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
    l_out := APEX_JSON.GET_CLOB_OUTPUT;
    APEX_JSON.FREE_OUTPUT;
    :status_code := 200;
    l_len := DBMS_LOB.GETLENGTH(l_out);
    WHILE l_pos <= l_len LOOP
        HTP.PRN(DBMS_LOB.SUBSTR(l_out, 8000, l_pos));
        l_pos := l_pos + 8000;
    END LOOP;
EXCEPTION WHEN OTHERS THEN
    :status_code := 500;
    HTP.PRN('{"success": false,"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );

    ORDS.DEFINE_PARAMETER(
        p_module_name        => 'reerp',
        p_pattern            => 'ar/buaccounts',
        p_method             => 'GET',
        p_name               => 'party_id',
        p_bind_variable_name => 'party_id',
        p_source_type        => 'URI',
        p_param_type         => 'STRING',
        p_access_method      => 'IN'
    );

-- ── 3. POST ar/buaccounts (first save for a BU) ────────────────────────────
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'ar/buaccounts',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Create a BU account assignment for a party',
        p_source         => q'[
DECLARE
    l_body CLOB := :body_text;
    l_id   NUMBER;
BEGIN
    INSERT INTO RR_BU_ACCOUNTS_ASSIGNMENTS (
        PARTY_ID, PARTY_NAME, BUSINESS_UNIT_NAME, COMPANY_CODE,
        RECEIVABLES_ACCOUNT, REVENUE_ACCOUNT, TAX_ACCOUNT, FREIGHT_ACCOUNT,
        UNBILLED_ACCOUNT, UNEARNED_ACCOUNT, CLEARING_ACCOUNT,
        STATUS, CREATED_BY, LAST_UPDATED_BY
    ) VALUES (
        JSON_VALUE(l_body, '$.partyId' RETURNING NUMBER),
        JSON_VALUE(l_body, '$.partyName'),
        JSON_VALUE(l_body, '$.businessUnitName'),
        JSON_VALUE(l_body, '$.companyCode'),
        JSON_VALUE(l_body, '$.receivablesAccount'),
        JSON_VALUE(l_body, '$.revenueAccount'),
        JSON_VALUE(l_body, '$.taxAccount'),
        JSON_VALUE(l_body, '$.freightAccount'),
        JSON_VALUE(l_body, '$.unbilledAccount'),
        JSON_VALUE(l_body, '$.unearnedAccount'),
        JSON_VALUE(l_body, '$.clearingAccount'),
        NVL(JSON_VALUE(l_body, '$.status'), 'ACTIVE'),
        NVL(JSON_VALUE(l_body, '$.createdBy'), 'REACTERP'),
        NVL(JSON_VALUE(l_body, '$.createdBy'), 'REACTERP')
    ) RETURNING ASSIGNMENT_ID INTO l_id;

    COMMIT;
    :status_code := 200;
    HTP.PRN('{"success": true,"assignmentId":' || l_id || '}');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        :status_code := 409;
        HTP.PRN('{"success": false,"error":"This business unit is already assigned to the party — use update instead"}');
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.PRN('{"success": false,"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ── 4. PUT ar/buaccounts/:assignmentId (subsequent saves) ──────────────────
BEGIN
    BEGIN
        ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ar/buaccounts/:assignmentId');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ar/buaccounts/:assignmentId');

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'ar/buaccounts/:assignmentId',
        p_method         => 'PUT',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Update a BU account assignment',
        p_source         => q'[
DECLARE
    l_body CLOB := :body_text;
    l_id   NUMBER := TO_NUMBER(:assignmentId);
    l_rows NUMBER;
BEGIN
    UPDATE RR_BU_ACCOUNTS_ASSIGNMENTS
       SET BUSINESS_UNIT_NAME  = NVL(JSON_VALUE(l_body, '$.businessUnitName'), BUSINESS_UNIT_NAME),
           COMPANY_CODE        = NVL(JSON_VALUE(l_body, '$.companyCode'), COMPANY_CODE),
           RECEIVABLES_ACCOUNT = JSON_VALUE(l_body, '$.receivablesAccount'),
           REVENUE_ACCOUNT     = JSON_VALUE(l_body, '$.revenueAccount'),
           TAX_ACCOUNT         = JSON_VALUE(l_body, '$.taxAccount'),
           FREIGHT_ACCOUNT     = JSON_VALUE(l_body, '$.freightAccount'),
           UNBILLED_ACCOUNT    = JSON_VALUE(l_body, '$.unbilledAccount'),
           UNEARNED_ACCOUNT    = JSON_VALUE(l_body, '$.unearnedAccount'),
           CLEARING_ACCOUNT    = JSON_VALUE(l_body, '$.clearingAccount'),
           STATUS              = NVL(JSON_VALUE(l_body, '$.status'), STATUS),
           LAST_UPDATED_BY     = NVL(JSON_VALUE(l_body, '$.updatedBy'), 'REACTERP'),
           LAST_UPDATE_DATE    = SYSTIMESTAMP
     WHERE ASSIGNMENT_ID = l_id;

    l_rows := SQL%ROWCOUNT;
    COMMIT;

    IF l_rows = 0 THEN
        :status_code := 404;
        HTP.PRN('{"success": false,"error":"Assignment not found","assignmentId":' || l_id || '}');
    ELSE
        :status_code := 200;
        HTP.PRN('{"success": true,"assignmentId":' || l_id || '}');
    END IF;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        :status_code := 409;
        HTP.PRN('{"success": false,"error":"This business unit is already assigned to the party"}');
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.PRN('{"success": false,"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ── Verify ─────────────────────────────────────────────────────────────────
--   GET  {base}/ar/buaccounts?party_id=300000003237680
--   POST {base}/ar/buaccounts
--        {"partyId":300000003237680,"partyName":"4S INTERNATIONAL LLC",
--         "businessUnitName":"BUIMERC CORP BU","companyCode":"01",
--         "receivablesAccount":"01-00-00-1210000-0000-000-00-000-000",
--         "revenueAccount":"01-00-00-4110000-0000-000-00-000-000",
--         "createdBy":"user@example.com"}
--   PUT  {base}/ar/buaccounts/1   (same body shape; updates the row)
--   SELECT * FROM RR_BU_ACCOUNTS_ASSIGNMENTS;
