-- =====================================================
-- AR Receipts — Multiple Credit Accounts
-- Table   : RR_AR_RECEIPTS_MULTIPLE_CREDITS
-- Parent  : RR_AR_RECEIPTS (STANDARD_RECEIPT_ID)
-- ORDS    : module 'ar'
--             GET  ar/receipts/:id/credits   — list credit lines
--             PUT  ar/receipts/:id/credits   — replace all lines (atomic,
--                                              validates sum = receipt amount)
-- A receipt is single-credit by default (CR_ACCOUNT on RR_AR_RECEIPTS).
-- When MULTI_CR_FLAG = 'Y' the credit side lives in this table instead.
-- =====================================================

-- DROP TABLE RR_AR_RECEIPTS_MULTIPLE_CREDITS CASCADE CONSTRAINTS;

CREATE TABLE RR_AR_RECEIPTS_MULTIPLE_CREDITS (
    CREDIT_LINE_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STANDARD_RECEIPT_ID   NUMBER         NOT NULL,
    RECEIPT_NUMBER        VARCHAR2(50),
    LINE_NUMBER           NUMBER         NOT NULL,
    CR_ACCOUNT            VARCHAR2(100)  NOT NULL,   -- GL code combination (segments joined by '-')
    CR_ACCOUNT_DESC       VARCHAR2(500),
    AMOUNT                NUMBER(18,2)   NOT NULL,
    CURRENCY              VARCHAR2(15),
    ACCOUNT_STATUS        VARCHAR2(20)   DEFAULT 'Unposted',   -- Unposted | Posted | Error
    COMMENTS              VARCHAR2(1000),
    CREATED_BY            VARCHAR2(240),
    CREATION_DATE         TIMESTAMP      DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY       VARCHAR2(240),
    LAST_UPDATE_DATE      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_AR_MULTI_CR_FK  FOREIGN KEY (STANDARD_RECEIPT_ID)
        REFERENCES RR_AR_RECEIPTS (STANDARD_RECEIPT_ID) ON DELETE CASCADE,
    CONSTRAINT RR_AR_MULTI_CR_AMT_CK CHECK (AMOUNT > 0),
    CONSTRAINT RR_AR_MULTI_CR_UK UNIQUE (STANDARD_RECEIPT_ID, LINE_NUMBER)
);

CREATE INDEX RR_AR_MULTI_CR_IX1 ON RR_AR_RECEIPTS_MULTIPLE_CREDITS (STANDARD_RECEIPT_ID);

COMMENT ON TABLE RR_AR_RECEIPTS_MULTIPLE_CREDITS IS
    'Credit-side GL distribution lines for AR receipts using multiple credit accounts (MULTI_CR_FLAG = Y on RR_AR_RECEIPTS)';

-- Flag on the parent: 'N' (default) = single Cr Account column, 'Y' = lines in this table
ALTER TABLE RR_AR_RECEIPTS ADD (
    MULTI_CR_FLAG  VARCHAR2(1) DEFAULT 'N'
);

-- =====================================================
-- ORDS: GET /ar/receipts/:id/credits
-- =====================================================
BEGIN
    ORDS.DELETE_TEMPLATE(p_module_name => 'ar', p_pattern => 'receipts/:id/credits');
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'ar',
        p_pattern     => 'receipts/:id/credits',
        p_comments    => 'Multiple credit account lines for one AR receipt'
    );
    COMMIT;
END;
/

BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name => 'ar',
        p_pattern     => 'receipts/:id/credits',
        p_method      => 'GET',
        p_source_type => 'json/collection',
        p_comments    => 'List credit lines for a receipt',
        p_source      => '
SELECT credit_line_id,
       standard_receipt_id,
       receipt_number,
       line_number,
       cr_account,
       cr_account_desc,
       amount,
       currency,
       account_status,
       comments,
       created_by,
       TO_CHAR(creation_date, ''YYYY-MM-DD HH24:MI:SS'') AS creation_date
FROM   rr_ar_receipts_multiple_credits
WHERE  standard_receipt_id = :id
ORDER BY line_number'
    );
    COMMIT;
END;
/

-- =====================================================
-- ORDS: PUT /ar/receipts/:id/credits
-- Body: {"updatedBy":"USER","lines":[{"crAccount":"01-...","crAccountDesc":"...","amount":100,"comments":null}, ...]}
-- Replaces ALL lines for the receipt atomically.
-- Validates: receipt exists, every line has account + amount > 0,
--            sum(lines) = receipt AMOUNT (0.01 tolerance).
-- Empty lines array deletes all lines and sets MULTI_CR_FLAG back to N.
-- =====================================================
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'ar',
        p_pattern        => 'receipts/:id/credits',
        p_method         => 'PUT',
        p_source_type    => 'plsql/block',
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Replace all credit lines for a receipt (atomic, sum must equal receipt amount)',
        p_source         => '
DECLARE
    l_body        CLOB := :body_text;
    l_receipt_id  NUMBER := :id;
    l_updated_by  VARCHAR2(240);
    l_receipt_amt NUMBER;
    l_receipt_no  VARCHAR2(50);
    l_currency    VARCHAR2(15);
    l_count       NUMBER;
    l_sum         NUMBER := 0;
    l_line_no     NUMBER := 0;
    l_acct        VARCHAR2(100);
    l_amount      NUMBER;
BEGIN
    APEX_JSON.PARSE(l_body);
    l_updated_by := NVL(APEX_JSON.GET_VARCHAR2(p_path => ''updatedBy''), ''SYSTEM'');
    l_count      := NVL(APEX_JSON.GET_COUNT(p_path => ''lines''), 0);

    BEGIN
        SELECT amount, receipt_number, currency
        INTO   l_receipt_amt, l_receipt_no, l_currency
        FROM   rr_ar_receipts
        WHERE  standard_receipt_id = l_receipt_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        :status_code := 404;
        HTP.P(''{"success":false,"message":"Receipt '' || l_receipt_id || '' not found"}'');
        RETURN;
    END;

    -- Validate every line before touching data
    FOR i IN 1 .. l_count LOOP
        l_acct   := APEX_JSON.GET_VARCHAR2(p_path => ''lines[%d].crAccount'', p0 => i);
        l_amount := APEX_JSON.GET_NUMBER  (p_path => ''lines[%d].amount'',    p0 => i);
        IF l_acct IS NULL OR l_amount IS NULL OR l_amount <= 0 THEN
            :status_code := 400;
            HTP.P(''{"success":false,"message":"Line '' || i || '': crAccount and a positive amount are required"}'');
            RETURN;
        END IF;
        l_sum := l_sum + l_amount;
    END LOOP;

    IF l_count > 0 AND ABS(l_sum - NVL(l_receipt_amt, 0)) > 0.01 THEN
        :status_code := 400;
        HTP.P(''{"success":false,"message":"Sum of credit lines ('' || TO_CHAR(l_sum) ||
              '') must equal receipt amount ('' || TO_CHAR(NVL(l_receipt_amt,0)) || '')"}'');
        RETURN;
    END IF;

    -- Atomic replace
    DELETE FROM rr_ar_receipts_multiple_credits
    WHERE  standard_receipt_id = l_receipt_id;

    FOR i IN 1 .. l_count LOOP
        l_line_no := l_line_no + 1;
        INSERT INTO rr_ar_receipts_multiple_credits (
            standard_receipt_id, receipt_number, line_number,
            cr_account, cr_account_desc, amount, currency,
            account_status, comments,
            created_by, last_updated_by, last_update_date
        ) VALUES (
            l_receipt_id, l_receipt_no, l_line_no,
            APEX_JSON.GET_VARCHAR2(p_path => ''lines[%d].crAccount'',     p0 => i),
            APEX_JSON.GET_VARCHAR2(p_path => ''lines[%d].crAccountDesc'', p0 => i),
            APEX_JSON.GET_NUMBER  (p_path => ''lines[%d].amount'',        p0 => i),
            l_currency,
            NVL(APEX_JSON.GET_VARCHAR2(p_path => ''lines[%d].accountStatus'', p0 => i), ''Unposted''),
            APEX_JSON.GET_VARCHAR2(p_path => ''lines[%d].comments'',      p0 => i),
            l_updated_by, l_updated_by, SYSTIMESTAMP
        );
    END LOOP;

    UPDATE rr_ar_receipts
    SET    multi_cr_flag    = CASE WHEN l_count > 0 THEN ''Y'' ELSE ''N'' END,
           last_updated_by  = l_updated_by,
           last_update_date = SYSTIMESTAMP
    WHERE  standard_receipt_id = l_receipt_id;

    COMMIT;
    :status_code := 200;
    HTP.P(''{"success":true,"receiptId":'' || l_receipt_id ||
          '',"lines":'' || l_count || '',"total":'' || TO_CHAR(l_sum) || ''}'');
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.P(''{"success":false,"message":"'' || REPLACE(SQLERRM, ''"'', ''\\"'') || ''"}'');
END;'
    );
    COMMIT;
END;
/
